<?php require_once __DIR__ . '/../Arquivos/verificarAdmin.php'; require_once __DIR__ . '/../Arquivos/conexao.php'; ?><!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Admin | HQ Universe</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Bangers&family=Bebas+Neue&family=Poppins:wght@300;400;600;700&display=swap" rel="stylesheet">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">

<link rel="stylesheet" href="../../CSS/admin.css?v=60">

  <link rel="stylesheet" href="../../CSS/estilo_jvrp.css?v=60">
  <link rel="stylesheet" href="../../CSS/funcionalidades.css?v=60">
</head><body class="pagina-admin">
  <?php require_once __DIR__ . '/../Arquivos/cabecalho.php'; ?>
  <?php mostrarFlash();?><main class="conteudo limite"><nav class="admin-menu"><a href="<?=url('Admin/index.php')?>">Dashboard</a><a href="<?=url('Admin/produtos.php')?>">Produtos</a><a href="<?=url('Admin/categorias.php')?>">Categorias</a><a href="<?=url('Admin/estoque.php')?>">Estoque</a><a href="<?=url('Admin/usuarios.php')?>">Usuários</a><a href="<?=url('Admin/pedidos.php')?>">Pedidos</a><a href="<?=url('loja.php')?>">Ver loja</a></nav><?php if($_SERVER['REQUEST_METHOD']==='POST'){try{$pdo->prepare('INSERT INTO categorias(nome,descricao) VALUES(?,?)')->execute([trim($_POST['nome']),trim($_POST['descricao'])]);flash('sucesso','Categoria criada.');header('Location: categorias.php');exit;}catch(Throwable $e){flash('erro','Categoria já existe.');}}$cs=$pdo->query('SELECT c.*,COUNT(p.id) produtos FROM categorias c LEFT JOIN produtos p ON p.categoria_id=c.id GROUP BY c.id')->fetchAll();?><h1>Categorias</h1><form method="post" class="formulario"><div class="form-grid"><div class="campo"><label>Nome</label><input name="nome" required></div><div class="campo"><label>Descrição</label><input name="descricao"></div></div><br><button class="botao">Adicionar</button></form><br><div class="tabela-caixa"><table class="tabela"><tr><th>Nome</th><th>Descrição</th><th>Produtos</th></tr><?php foreach($cs as $c):?><tr><td><?=e($c['nome'])?></td><td><?=e($c['descricao'])?></td><td><?=$c['produtos']?></td></tr><?php endforeach;?></table></div></main><?php require_once __DIR__ . '/../Arquivos/rodape.php';?>  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body></html>