<?php require_once __DIR__ . '/../Arquivos/verificarAdmin.php'; require_once __DIR__ . '/../Arquivos/conexao.php'; ?><!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Admin | HQ Universe</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Bangers&family=Bebas+Neue&family=Poppins:wght@300;400;600;700&display=swap" rel="stylesheet">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">

<link rel="stylesheet" href="../../CSS/admin.css?v=60">

  <link rel="stylesheet" href="../../CSS/estilo_jvrp.css?v=60">
  <link rel="stylesheet" href="../../CSS/funcionalidades.css?v=60">
</head><body class="pagina-admin">
  <?php require_once __DIR__ . '/../Arquivos/cabecalho.php'; ?>
  <?php mostrarFlash();?><main class="conteudo limite"><nav class="admin-menu"><a href="<?=url('Admin/index.php')?>">Dashboard</a><a href="<?=url('Admin/produtos.php')?>">Produtos</a><a href="<?=url('Admin/categorias.php')?>">Categorias</a><a href="<?=url('Admin/estoque.php')?>">Estoque</a><a href="<?=url('Admin/usuarios.php')?>">Usuários</a><a href="<?=url('Admin/pedidos.php')?>">Pedidos</a><a href="<?=url('loja.php')?>">Ver loja</a></nav><?php $ps=$pdo->query('SELECT p.*,u.nome usuario,f.nome forma FROM pedidos p JOIN usuarios u ON u.id=p.usuario_id JOIN formas_pagamento f ON f.id=p.forma_pagamento_id ORDER BY p.id DESC')->fetchAll();?><h1>Pedidos</h1><div class="tabela-caixa"><table class="tabela"><tr><th>Pedido</th><th>Cliente</th><th>Data</th><th>Total</th><th>Pagamento</th><th>Status</th></tr><?php foreach($ps as $p):?><tr><td>#<?=$p['id']?></td><td><?=e($p['usuario'])?></td><td><?=date('d/m/Y H:i',strtotime($p['data_pedido']))?></td><td><?=moeda((float)$p['valor_total'])?></td><td><?=e($p['forma'])?></td><td><form action="pedido_status.php" method="post"><input type="hidden" name="id" value="<?=$p['id']?>"><select name="status" onchange="this.form.submit()"><?php foreach(['pendente','pago','enviado','entregue','cancelado'] as $s):?><option <?=$s===$p['status']?'selected':''?>><?=$s?></option><?php endforeach;?></select></form></td></tr><?php endforeach;?></table></div></main><?php require_once __DIR__ . '/../Arquivos/rodape.php';?>  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body></html>