<?php require_once __DIR__ . '/../Arquivos/verificarAdmin.php'; require_once __DIR__ . '/../Arquivos/conexao.php'; ?><!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Admin | HQ Universe</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Bangers&family=Bebas+Neue&family=Poppins:wght@300;400;600;700&display=swap" rel="stylesheet">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">

<link rel="stylesheet" href="../../CSS/admin.css?v=60">

  <link rel="stylesheet" href="../../CSS/estilo_jvrp.css?v=60">
  <link rel="stylesheet" href="../../CSS/funcionalidades.css?v=60">
</head><body class="pagina-admin">
  <?php require_once __DIR__ . '/../Arquivos/cabecalho.php'; ?>
  <?php mostrarFlash();?><main class="conteudo limite"><nav class="admin-menu"><a href="<?=url('Admin/index.php')?>">Dashboard</a><a href="<?=url('Admin/produtos.php')?>">Produtos</a><a href="<?=url('Admin/categorias.php')?>">Categorias</a><a href="<?=url('Admin/estoque.php')?>">Estoque</a><a href="<?=url('Admin/usuarios.php')?>">Usuários</a><a href="<?=url('Admin/pedidos.php')?>">Pedidos</a><a href="<?=url('loja.php')?>">Ver loja</a></nav><?php $ps=$pdo->query('SELECT p.*,c.nome categoria,COALESCE(e.quantidade,0) estoque FROM produtos p JOIN categorias c ON c.id=p.categoria_id LEFT JOIN estoque e ON e.produto_id=p.id ORDER BY p.id DESC')->fetchAll();?><h1>Produtos</h1><p><a class="botao" href="produto_form.php">Adicionar produto</a></p><div class="tabela-caixa"><table class="tabela"><tr><th>ID</th><th>Produto</th><th>Categoria</th><th>Preço</th><th>Estoque</th><th>Ações</th></tr><?php foreach($ps as $p):?><tr><td><?=$p['id']?></td><td><?=e($p['nome'])?></td><td><?=e($p['categoria'])?></td><td><?=moeda((float)$p['preco'])?></td><td><?=$p['estoque']?></td><td><a href="produto_form.php?id=<?=$p['id']?>">Editar</a> · <a href="produto_excluir.php?id=<?=$p['id']?>" onclick="return confirm('Excluir?')">Excluir</a></td></tr><?php endforeach;?></table></div></main><?php require_once __DIR__ . '/../Arquivos/rodape.php';?>  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body></html>