<?php require_once __DIR__ . '/../Arquivos/verificarAdmin.php'; require_once __DIR__ . '/../Arquivos/conexao.php'; ?><!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Admin | HQ Universe</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Bangers&family=Bebas+Neue&family=Poppins:wght@300;400;600;700&display=swap" rel="stylesheet">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">

<link rel="stylesheet" href="../../CSS/admin.css?v=60">

  <link rel="stylesheet" href="../../CSS/estilo_jvrp.css?v=60">
  <link rel="stylesheet" href="../../CSS/funcionalidades.css?v=60">
</head><body class="pagina-admin">
  <?php require_once __DIR__ . '/../Arquivos/cabecalho.php'; ?>
  <?php mostrarFlash();?><main class="conteudo limite"><nav class="admin-menu"><a href="<?=url('Admin/index.php')?>">Dashboard</a><a href="<?=url('Admin/produtos.php')?>">Produtos</a><a href="<?=url('Admin/categorias.php')?>">Categorias</a><a href="<?=url('Admin/estoque.php')?>">Estoque</a><a href="<?=url('Admin/usuarios.php')?>">Usuários</a><a href="<?=url('Admin/pedidos.php')?>">Pedidos</a><a href="<?=url('loja.php')?>">Ver loja</a></nav><?php $id=filter_input(INPUT_GET,'id',FILTER_VALIDATE_INT);$p=['id'=>'','categoria_id'=>'','nome'=>'','autor'=>'','editora'=>'','isbn'=>'','descricao'=>'','preco'=>'','imagem'=>'','ativo'=>1,'quantidade'=>0];if($id){$st=$pdo->prepare('SELECT p.*,COALESCE(e.quantidade,0) quantidade FROM produtos p LEFT JOIN estoque e ON e.produto_id=p.id WHERE p.id=?');$st->execute([$id]);$p=$st->fetch()?:$p;}$cats=$pdo->query('SELECT * FROM categorias WHERE ativo=1 ORDER BY nome')->fetchAll();?><form class="formulario" method="post" action="produto_salvar.php" enctype="multipart/form-data"><h1><?=$id?'Editar':'Adicionar'?> produto</h1><input type="hidden" name="id" value="<?=e((string)$p['id'])?>"><div class="form-grid"><div class="campo"><label>Nome</label><input name="nome" value="<?=e($p['nome'])?>" required></div><div class="campo"><label>Categoria</label><select name="categoria_id" required><?php foreach($cats as $c):?><option value="<?=$c['id']?>" <?=$c['id']==$p['categoria_id']?'selected':''?>><?=e($c['nome'])?></option><?php endforeach;?></select></div><div class="campo"><label>Autor</label><input name="autor" value="<?=e($p['autor'])?>"></div><div class="campo"><label>Editora</label><input name="editora" value="<?=e($p['editora'])?>"></div><div class="campo"><label>ISBN</label><input name="isbn" value="<?=e($p['isbn'])?>"></div><div class="campo"><label>Preço</label><input type="number" step="0.01" min="0" name="preco" value="<?=e((string)$p['preco'])?>" required></div><div class="campo"><label>Estoque</label><input type="number" min="0" name="quantidade" value="<?=e((string)$p['quantidade'])?>"></div><div class="campo"><label>Imagem</label><input type="file" name="imagem" accept="image/*"><small>Atual: <?=e($p['imagem'])?></small><input type="hidden" name="imagem_atual" value="<?=e($p['imagem'])?>"></div><div class="campo campo-total"><label>Descrição</label><textarea name="descricao"><?=e($p['descricao'])?></textarea></div><div class="campo"><label><input type="checkbox" name="ativo" value="1" <?=$p['ativo']?'checked':''?>> Produto ativo</label></div></div><br><button class="botao">Salvar</button></form></main><?php require_once __DIR__ . '/../Arquivos/rodape.php';?>  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body></html>