<?php require_once __DIR__ . '/../Arquivos/verificarAdmin.php'; require_once __DIR__ . '/../Arquivos/conexao.php'; ?><!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Admin | HQ Universe</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Bangers&family=Bebas+Neue&family=Poppins:wght@300;400;600;700&display=swap" rel="stylesheet">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">

<link rel="stylesheet" href="../../CSS/admin.css?v=60">

  <link rel="stylesheet" href="../../CSS/estilo_jvrp.css?v=60">
  <link rel="stylesheet" href="../../CSS/funcionalidades.css?v=60">
</head><body class="pagina-admin">
  <?php require_once __DIR__ . '/../Arquivos/cabecalho.php'; ?>
  <?php mostrarFlash();?><main class="conteudo limite"><nav class="admin-menu"><a href="<?=url('Admin/index.php')?>">Dashboard</a><a href="<?=url('Admin/produtos.php')?>">Produtos</a><a href="<?=url('Admin/categorias.php')?>">Categorias</a><a href="<?=url('Admin/estoque.php')?>">Estoque</a><a href="<?=url('Admin/usuarios.php')?>">Usuários</a><a href="<?=url('Admin/pedidos.php')?>">Pedidos</a><a href="<?=url('loja.php')?>">Ver loja</a></nav><?php if(isset($_GET['alternar'])){$id=(int)$_GET['alternar'];if($id!==$_SESSION['id'])$pdo->prepare('UPDATE usuarios SET ativo=1-ativo WHERE id=?')->execute([$id]);header('Location: usuarios.php');exit;}$us=$pdo->query('SELECT * FROM usuarios ORDER BY id DESC')->fetchAll();?><h1>Usuários</h1><div class="tabela-caixa"><table class="tabela"><tr><th>Nome</th><th>Usuário</th><th>E-mail</th><th>Tipo</th><th>Status</th><th>Ação</th></tr><?php foreach($us as $u):?><tr><td><?=e($u['nome'].' '.$u['sobrenome'])?></td><td><?=e($u['usuario'])?></td><td><?=e($u['email'])?></td><td><?=e($u['tipo'])?></td><td><?=$u['ativo']?'Ativo':'Inativo'?></td><td><?php if($u['id']!==$_SESSION['id']):?><a href="?alternar=<?=$u['id']?>"><?=$u['ativo']?'Desativar':'Ativar'?></a><?php endif;?></td></tr><?php endforeach;?></table></div></main><?php require_once __DIR__ . '/../Arquivos/rodape.php';?>  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body></html>