<?php
// Catálogo estático reorganizado: Mangá (1-64), Marvel (65-93), DC Comics (94-125).
return [
  1 => ['categoria_id' => 1, 'nome' => 'Ataque dos titãs vol. 34', 'autor' => 'Hajime Isayama', 'ano_publicacao' => 2022, 'paginas' => 256, 'isbn' => '9786559606948', 'editora' => 'Panini', 'descricao' => 'O Estrondo esmagou as terras além da Ilha Paradis e tomou inúmeras vidas. Por um lado Armin, Mikasa e os outros descobrem em qual ponto devem atacar Eren. Inimigos, aliados, companheiros e tantas vidas perdidas depois, eles finalmente conseguem chegar até Eren.', 'preco' => 24.90, 'imagem' => 'attack_on_titan_34.jpg', 'link_compra' => '../compra/attackontitan_34.php'],
  2 => ['categoria_id' => 1, 'nome' => 'Attack on Titan 33', 'autor' => 'Hajime Isayama', 'ano_publicacao' => 2021, 'paginas' => 192, 'isbn' => 'Edição impressa — ISBN específico da tiragem', 'editora' => 'Panini', 'descricao' => 'Eren dá continuidade ao estrondo para destruir todas as terras além da Ilha Paradis. Para alcançá-lo, Mikasa, Armin e o grupo vão para a cidade de Odiha onde a aeronave poderá ser preparada. Porém, o preço a ser pago será desistir de Revelio, a cidade onde as famílias do grupo de Annie e Reiner vivem...', 'preco' => 122.85, 'imagem' => 'attack_on_titan_33.jpg', 'link_compra' => '../compra/attackontitan_33.php'],
  3 => ['categoria_id' => 1, 'nome' => 'Attack on Titan 32', 'autor' => 'Hajime Isayama', 'ano_publicacao' => 2021, 'paginas' => 192, 'isbn' => 'Edição impressa — ISBN específico da tiragem', 'editora' => 'Panini', 'descricao' => 'Para proteger a paz da Ilha Paradis, Eren decide exterminar a humanidade fora da ilha com o poder do Titã Original. Ele inicia seu ataque, seguido por inúmeros titãs. Serão eles heróis ou demônios? Sem chegar a uma conclusão, Mikasa, Armin e o resto do grupo se preparam para salvar o mundo.', 'preco' => 72.98, 'imagem' => 'attack_on_titan_32.jpg', 'link_compra' => '../compra/attackontitan_32.php'],
  4 => ['categoria_id' => 1, 'nome' => 'Attack on Titan 31', 'autor' => 'Hajime Isayama', 'ano_publicacao' => 2021, 'paginas' => 192, 'isbn' => 'Edição impressa — ISBN específico da tiragem', 'editora' => 'Panini', 'descricao' => 'Após romper as defesas de antigos amigos e inimigos, Zeke revela seu plano para os Eldianos a Eren. Mas o que Eren planejava com seus poderes estrondosos deixa seu irmão para trás, traído e sozinho mais uma vez. Agora, com a ajuda de Ymir, uma horda de Titãs gigantescos desperta de seu sono secular, rompendo as Muralhas para atender ao chamado de seu fundador. Para onde essa marcha os levará, só Eren sabe...', 'preco' => 136.43, 'imagem' => 'attack_on_titan_31.jpg', 'link_compra' => '../compra/attackontitan_31.php'],
  5 => ['categoria_id' => 1, 'nome' => 'Attack on Titan 1', 'autor' => 'Hajime Isayama', 'ano_publicacao' => 2021, 'paginas' => 192, 'isbn' => 'Edição impressa — ISBN específico da tiragem', 'editora' => 'Panini', 'descricao' => 'Nesta história de ficção científica pós-apocalíptica, a humanidade foi devastada pelos bizarros humanoides gigantes conhecidos como Titãs. Pouco se sabe sobre sua origem ou por que estão empenhados em consumir a humanidade. Aparentemente sem inteligência, eles vagam pelo mundo há anos, matando todos que encontram. Durante o último século, o que restou da humanidade se escondeu em uma gigantesca cidade murada. As pessoas acreditam que suas muralhas de 100 metros de altura as protegerão dos Titãs, mas o súbito aparecimento de um Titã imenso está prestes a mudar tudo.', 'preco' => 49, 'imagem' => 'attack_on_titan_1.jpg', 'link_compra' => '../compra/attackontitan_1.php'],
  6 => ['categoria_id' => 1, 'nome' => 'Attack on Titan 2', 'autor' => 'Hajime Isayama', 'ano_publicacao' => 2021, 'paginas' => 192, 'isbn' => 'Edição impressa — ISBN específico da tiragem', 'editora' => 'Panini', 'descricao' => 'O Titã Colossal rompeu a primeira linha de defesa da humanidade, a Muralha Maria. Mikasa, a ás do 104º Corpo de Treinamento e melhor amiga de Eren, pode ser a única capaz de derrotá-los, mas por trás de sua calma aparente, esconde-se um passado sombrio. Quando tudo parece perdido, um novo Titã surge e começa a massacrar seus companheiros. Será que esse novo monstro é uma bênção disfarçada, ou a verdade é algo muito mais sinistro?', 'preco' => 72.98, 'imagem' => 'attack_on_titan_2.jpg', 'link_compra' => '../compra/attackontitan_2.php'],
  7 => ['categoria_id' => 1, 'nome' => 'Attack on Titan 3', 'autor' => 'Hajime Isayama', 'ano_publicacao' => 2021, 'paginas' => 192, 'isbn' => 'Edição impressa — ISBN específico da tiragem', 'editora' => 'Panini', 'descricao' => 'A última coisa que Eren se lembra antes de desmaiar é de um Titã arrancando seu braço e perna com uma mordida e se preparando para devorá-lo vivo. Para sua surpresa, ele acorda sem um arranhão sequer, cercado por uma multidão de soldados enfurecidos que clamam por seu sangue. Que estranho novo poder ele despertou, e o que acontecerá quando o garoto devotado a destruir os Titãs se tornar um deles?', 'preco' => 59.25, 'imagem' => 'attack_on_titan_3.jpg', 'link_compra' => '../compra/attackontitan_3.php'],
  8 => ['categoria_id' => 1, 'nome' => 'Attack on Titan 4', 'autor' => 'Hajime Isayama', 'ano_publicacao' => 2021, 'paginas' => 192, 'isbn' => 'Edição impressa — ISBN específico da tiragem', 'editora' => 'Panini', 'descricao' => 'O Corpo de Investigação elabora uma estratégia arriscada: enviar Eren, em sua forma Titã, para tentar reparar a Muralha Rose, recuperando o território humano dos monstros pela primeira vez em um século. Mas o autocontrole de Eren em forma de Titã está longe de ser perfeito, e quando ele entra em fúria, nem mesmo Armin consegue detê-lo! Com a sobrevivência da humanidade em seus ombros gigantescos, será que Eren conseguirá recuperar o juízo, ou se perderá para sempre?', 'preco' => 60.20, 'imagem' => 'attack_on_titan_4.jpg', 'link_compra' => '../compra/attackontitan_4.php'],
  9 => ['categoria_id' => 1, 'nome' => 'Bleach, Vol. 33: The Bad Joke', 'autor' => 'Tite Kubo', 'ano_publicacao' => 2021, 'paginas' => 192, 'isbn' => 'Edição impressa — ISBN específico da tiragem', 'editora' => 'Panini', 'descricao' => 'A missão de Ichigo para resgatar sua amiga Orihime do mundo Hollow se transformou em uma luta pela sobrevivência contra uma sucessão de inimigos, cada um mais poderoso que o anterior. Agora mais um desafiante feroz entrou na disputa, um que por acaso conhece a surpreendente verdade sobre a nova amiga de Ichigo, Nel!', 'preco' => 46.90, 'imagem' => 'bleach_33.jpg', 'link_compra' => '../compra/bleach_vol33.php'],
  10 => ['categoria_id' => 1, 'nome' => 'Bleach, Vol. 35: HIGHER THAN THE MOON', 'autor' => 'Tite Kubo', 'ano_publicacao' => 2021, 'paginas' => 192, 'isbn' => 'Edição impressa — ISBN específico da tiragem', 'editora' => 'Panini', 'descricao' => 'Ceifadores de Almas estão envolvidos em sangrentas batalhas um contra um com os Espadas, seu inimigo jurado Aizen se prepara para fazer o próximo movimento em seu elaborado plano. Os campos de batalha de Hueco Mundo logo darão lugar a outro campo de batalha onde o preço da derrota será infinitamente maior. Enquanto os Ceifadores de Almas estão envolvidos em sangrentas batalhas um contra um com os Espadas, seu inimigo jurado Aizen se prepara para fazer o próximo movimento em seu elaborado plano. Os campos de batalha de Hueco Mundo logo darão lugar a outro campo de batalha onde o preço da derrota será infinitamente maior.', 'preco' => 59.57, 'imagem' => 'bleach_35.jpg', 'link_compra' => '../compra/bleach_vol35.php'],
  11 => ['categoria_id' => 1, 'nome' => 'Bleach, Vol. 36: Turn Back the Pendulum', 'autor' => 'Tite Kubo', 'ano_publicacao' => 2021, 'paginas' => 192, 'isbn' => 'Edição impressa — ISBN específico da tiragem', 'editora' => 'Panini', 'descricao' => 'Descubra o que aconteceu na Soul Society há cem anos. Kisuke Urahara é o novo capitão da décima segunda companhia — agora se ao menos ele pudesse se dar bem com seu capitão assistente. E o capitão Soul Reaper, Shinji Hirako, suspeita que algo sinistro está acontecendo com seu segundo em comando, Aizen.', 'preco' => 19.90, 'imagem' => 'bleach_36.jpg', 'link_compra' => '../compra/bleach_vol36.php'],
  12 => ['categoria_id' => 1, 'nome' => 'Bleach, Vol. 37: Beauty Is So Solitary', 'autor' => 'Tite Kubo', 'ano_publicacao' => 2021, 'paginas' => 192, 'isbn' => 'Edição impressa — ISBN específico da tiragem', 'editora' => 'Panini', 'descricao' => 'O capitão dos Ceifadores de Almas, Shinji Hirako, descobriu a traição de Aizen, mas pode ser tarde demais. À medida que alguns dos maiores Ceifadores de Almas da Soul Society se transformam em Hollows, cabe a Kisuke Urahara salvá-los. E de volta ao presente, a grande batalha entre as Treze Companhias da Guarda da Corte e os Espada restantes finalmente começa!', 'preco' => 61.74, 'imagem' => 'bleach_37.jpg', 'link_compra' => '../compra/bleach_vol37.php'],
  13 => ['categoria_id' => 1, 'nome' => 'Bleach, Vol. 1: Strawberry and the Soul Reapers', 'autor' => 'Tite Kubo', 'ano_publicacao' => 2021, 'paginas' => 192, 'isbn' => 'Edição impressa — ISBN específico da tiragem', 'editora' => 'Panini', 'descricao' => 'Ichigo Kurosaki, de temperamento explosivo, herói da popular aventura fantástica Bleach, tem a inquietante habilidade de enxergar espíritos que não conseguem descansar em paz. Seu sexto sentido o leva até Rukia, uma Ceifadora de Almas que destrói Hollows (monstros devoradores de almas) e garante que os mortos encontrem repouso junto à Sociedade das Almas. Quando ela se machuca em batalha, Rukia transfere sua espada e grande parte de seu poder para Ichigo, cuja energia espiritual o torna um formidável Ceifador de Almas. Mas o adolescente de cabelos laranja não tem certeza se quer o cargo: riscos demais e dilemas morais.', 'preco' => 58.11, 'imagem' => 'bleach_1.jpg', 'link_compra' => '../compra/bleach_vol1.php'],
  14 => ['categoria_id' => 1, 'nome' => 'Bleach vol. 2', 'autor' => 'Tite Kubo', 'ano_publicacao' => 2021, 'paginas' => 192, 'isbn' => 'Edição impressa — ISBN específico da tiragem', 'editora' => 'Panini', 'descricao' => 'A turma E compete com a turma A por clientes para a sua barraca no Festival da Escola. Apesar da localização pouco central, a barraca da turma E é muito concorrido, até que um grupo de aluno aparece para fazer uma visita com consequências surpreendentes.', 'preco' => 29.90, 'imagem' => 'bleach_2.jpg', 'link_compra' => '../compra/bleach_vol2.php'],
  15 => ['categoria_id' => 1, 'nome' => 'Bleach vol. 3', 'autor' => 'Tite Kubo', 'ano_publicacao' => 2021, 'paginas' => 192, 'isbn' => 'Edição impressa — ISBN específico da tiragem', 'editora' => 'Panini', 'descricao' => 'Ichigo já estava acostumado com a ideia de que podia ver fantasmas, mas, quando conheceu Rukia, descobriu que o mundo espiritual é muito mais complexo do que imaginava! Para ajudar a shinigami (uma espécie de "policial espiritual"), Ichigo concordou em ser transformado em shinigami e derrotou o hollow que atormentava sua família. Durante seu treinamento para esse "trabalho espiritual", enfrentou seus primeiros desafios, que envolveram seus colegas de classe Orihime e Chad, e não foram nada fáceis! Tanto é que Rukia precisou ir à Loja Urahara para poder reabastecer suas geringonças. Nessa, Rukia adquiriu uma alma compactada para habitar o corpo de Ichigo enquanto ele realizava suas missões. Porém, após muita confusão descobriu que se tratava de uma Alma Modificada, louca para viver cuja existência havia sido proibida! Mas... o que fazer com uma alma originalmente sem corpo?', 'preco' => 77, 'imagem' => 'bleach_3.jpg', 'link_compra' => '../compra/bleach_vol3.php'],
  16 => ['categoria_id' => 1, 'nome' => 'Bleach vol. 4', 'autor' => 'Tite Kubo', 'ano_publicacao' => 2021, 'paginas' => 192, 'isbn' => 'Edição impressa — ISBN específico da tiragem', 'editora' => 'Panini', 'descricao' => 'Allen desapareceu. Lavi e Lenalee vão atrás dele, mas acabam confrontando a horda de akuma que persegue o golem de Allen, Timcanpy. Depois de cuidar disso, recebem a ordem de continuar a missão sem Allen, sendo que seu lugar é tomado por uma nova exorcista, Miranda Lotto. Allen, enquanto isso, desperta na Sucursal Asiática da Ordem Negra e se depara com a dura realidade de que perdeu a sua Innocence!', 'preco' => 55, 'imagem' => 'bleach_4.jpg', 'link_compra' => '../compra/bleach_vol4.php'],
  17 => ['categoria_id' => 1, 'nome' => 'Demon Slayer - Kimetsu no Yaiba Vol. 23', 'autor' => 'Koyoharu Gotouge', 'ano_publicacao' => 2022, 'paginas' => 232, 'isbn' => '9786559606986', 'editora' => 'Panini', 'descricao' => 'A batalha entre Muzan Kibutsuji, o progenitor dos Onis e Tanjirou e o Kisatsutai ruma para a sua conclusão!! Os quatro tipos de remédios que 
        Tamayo conseguiu inocular no corpo de Muzan fizeram com que ele enfraquecesse e finalmente fosse encurralado! Qual será o destino de Tanjirou, Nezuko e do Kisatsutai?! 
        O longo confronto contra os Onis finalmente está chegando ao seu fim!!', 'preco' => 200, 'imagem' => 'demonslayer_vol23.jpg', 'link_compra' => '../compra/demon_slayer_vol23.php'],
  18 => ['categoria_id' => 1, 'nome' => 'Demon slayer - Kimetsu no Yaiba vol. 18', 'autor' => 'Koyoharu Gotouge', 'ano_publicacao' => 2021, 'paginas' => 192, 'isbn' => '9786559822676', 'editora' => 'Panini', 'descricao' => 'Tanjirou e Giyu estão travando uma luta árdua contra Akaza, o Terceiro Jougen! Ambos conseguem apenas ficar na defensiva diante de todo o 
        poder avassalador de Akaza, mas é no calor desse confronto sem igual que Tanjirou adentra o "Mundo Transparente" mencionado por seu pai! Será que finalmente a katana 
        de Tanjirou conseguirá ferir Akaza?!', 'preco' => 39.04, 'imagem' => 'demon_slayer_vol18.jpg', 'link_compra' => '../compra/demon_slayer_vol18.php'],
  19 => ['categoria_id' => 1, 'nome' => 'Demon Slayer: Kimetsu No Yaiba, Vol. 19', 'autor' => 'Koyoharu Gotouge', 'ano_publicacao' => 2021, 'paginas' => 192, 'isbn' => '9786559821402', 'editora' => 'Panini', 'descricao' => 'A batalha entre Kanao e Inosuke contra Doma, o Segundo Jougen, chega ao seu clímax! Ambos os combatentes do Kisatsutai se veem em um confronto terrível 
        tendo que lidar com os inúmeros Jutsus de Sangue Demoníaco do oni que matou seus parentes! Diante de tanta desvantagem, será que eles conseguirão evitar a derrota?!', 'preco' => 42.65, 'imagem' => 'demon_slayer_vol19.jpg', 'link_compra' => '../compra/demon_slayer_vol19.php'],
  20 => ['categoria_id' => 1, 'nome' => 'Demon Slayer: Kimetsu No Yaiba, Vol. 20', 'autor' => 'Koyoharu Gotouge', 'ano_publicacao' => 2021, 'paginas' => 192, 'isbn' => '9786559820184', 'editora' => 'Panini', 'descricao' => 'Himejima, o Hashira das Rochas e Shinazugawa, o Hashira do Vento estão enfrentando o Primeiro Jougen! Durante essa dificílima batalha, ambos manifestam a marca e complementam as habilidades um do outro num fantástico trabalho em equipe, mas mesmo assim, continuam sendo terrivelmente pressionados pela força avassaladora do Oni!! Até que Genya consome parte do Primeiro Jougen e se recupera... Qual será a conclusão da batalha?!', 'preco' => 42, 'imagem' => 'demon_slayer_vol20.jpg', 'link_compra' => '../compra/demon_slayer_vol20.php'],
  21 => ['categoria_id' => 1, 'nome' => 'Demon slayer - Kimetsu No Yaiba vol. 1', 'autor' => 'Koyoharu Gotouge', 'ano_publicacao' => 2024, 'paginas' => 192, 'isbn' => '9788542629286', 'editora' => 'Panini', 'descricao' => 'Estamos na Era Taishou. O dia-a-dia pacato de Tanjiro, um gentil garoto que vende carvão, se transforma radicalmente quando sua família é assassinada por um demônio. A única sobrevivente é Nezuko, sua irmã mais nova. Porém, agora, ela se transformou em um Oni. Diante dessa tragédia, os dois irmãos partem em uma jornada para derrotar o Oni que matou sua mãe e irmãozinhos. E assim tem início uma aventura sanguinolenta de espadachins!', 'preco' => 35, 'imagem' => 'demon_slayer_vol1.jpg', 'link_compra' => '../compra/demon_slayer_vol1.php'],
  22 => ['categoria_id' => 1, 'nome' => 'Demon slayer - Kimetsu No Yaiba vol. 2', 'autor' => 'Koyoharu Gotouge', 'ano_publicacao' => 2020, 'paginas' => 192, 'isbn' => '9788542629880', 'editora' => 'Panini', 'descricao' => 'Tanjiro irá se valer de uma técnica ensinada por seu mestre Urokodaki para derrotar o oni na última etapa do teste para ingressar no Kissatsutai. Após isso, ele e Nezuko, agora acordada, irão para uma cidade em que as meninas jovens estão misteriosamente desaparecendo... Qual será o mistério detrás disso?!', 'preco' => 33.53, 'imagem' => 'demon_slayer_vol2.jpg', 'link_compra' => '../compra/demon_slayer_vol2.php'],
  23 => ['categoria_id' => 1, 'nome' => 'Demon slayer - Kimetsu No Yaiba Vol. 3', 'autor' => 'Koyoharu Gotouge', 'ano_publicacao' => 2021, 'paginas' => 192, 'isbn' => '9786555120271', 'editora' => 'Panini', 'descricao' => 'Tanjirou e Nezuko cruzam caminho com onis que manipulam armas misteriosas e são subordinados diretos de Kibutsuji. Mesmo a ajuda de Tamayo e Yushirou pode não ser o bastante para enfrentá-los!! Será que eles conseguirão pistas para chegar ao seu arqui-inimigo Kibutsuji?!', 'preco' => 34.90, 'imagem' => 'demon_slayer_vol3.jpg', 'link_compra' => '../compra/demon_slayer_vol3.php'],
  24 => ['categoria_id' => 1, 'nome' => 'Demon slayer - Kimetsu No Yaiba vol. 4', 'autor' => 'Koyoharu Gotouge', 'ano_publicacao' => 2020, 'paginas' => 192, 'isbn' => '9786555120301', 'editora' => 'Panini', 'descricao' => 'Depois de ter saído da casa do oni que manipulava o tsuzumi, Tanjirou viu Zenitsu sofrer ataques de um rapaz vestindo uma máscara de javali sem revidar. Conseguirá Tanjirou impedi-lo?! E após um breve período de descanso, o garoto e seus companheiros partem rumo a uma montanha sinistra em uma missão de emergência designada pelo Esquadrão de Exterminadores de Onis, o Kisatsutai!! O que estará escondido lá...?!', 'preco' => 31.14, 'imagem' => 'demon_slayer_vol4.jpg', 'link_compra' => '../compra/demon_slayer_vol4.php'],
  25 => ['categoria_id' => 1, 'nome' => 'Dragon Ball - 42', 'autor' => 'Akira Toriyama', 'ano_publicacao' => 2021, 'paginas' => 192, 'isbn' => '9786559601523', 'editora' => 'Panini', 'descricao' => 'O confronto com Majin Boo chega ao fim... Se nossos amigos não conseguirem derrotá-lo, será realmente o fim para a Terra e todo o universo!', 'preco' => 60, 'imagem' => 'dragon_ball_42.jpg', 'link_compra' => '../compra/dragonballZ_vol42.php'],
  26 => ['categoria_id' => 1, 'nome' => 'Dragon Ball - 41', 'autor' => 'Akira Toriyama', 'ano_publicacao' => 2021, 'paginas' => 192, 'isbn' => '9786559601547', 'editora' => 'Panini', 'descricao' => 'Piccolo convence Majin Boo a lutar na Sala do Espírito e Tempo contra Trunks e Goten, que se juntaram usando a técnica de fusão. Os dois jovens serão capazes de vencer esse monstro terrível?', 'preco' => 60, 'imagem' => 'dragon_ball_41.jpg', 'link_compra' => '../compra/dragonballZ_vol41.php'],
  27 => ['categoria_id' => 1, 'nome' => 'Dragon Ball - 40', 'autor' => 'Akira Toriyama', 'ano_publicacao' => 2021, 'paginas' => 192, 'isbn' => '9786559600861', 'editora' => 'Panini', 'descricao' => 'Boo está destruindo o planeta e a esperança está nas mãos de duas crianças: Goten e Trunks!', 'preco' => 60, 'imagem' => 'dragon_ball_40.jpg', 'link_compra' => '../compra/dragonballZ_vol40.php'],
  28 => ['categoria_id' => 1, 'nome' => 'Dragon Ball - 39', 'autor' => 'Akira Toriyama', 'ano_publicacao' => 2021, 'paginas' => 192, 'isbn' => '9786559600977', 'editora' => 'Panini', 'descricao' => 'O mal supremo despertou de seu longo sono! Agora, Goku e seus amigos precisarão encontrar um meio de enfrentar o temível Majin Boo, que, apesar da aparência, possui um poder devastador! Será que há esperanças para os nossos guerreiros?!', 'preco' => 60, 'imagem' => 'dragon_ball_39.jpg', 'link_compra' => '../compra/dragonballZ_vol39.php'],
  29 => ['categoria_id' => 1, 'nome' => 'Dragon Ball - 01', 'autor' => 'Akira Toriyama', 'ano_publicacao' => 2021, 'paginas' => 192, 'isbn' => 'Edição impressa — ISBN específico da tiragem', 'editora' => 'Panini', 'descricao' => 'Son Goku é um pequeno órfão de coração puro, mas com uma tremenda força. Depois de viver tanto tempo isolado da civilização, ele recebe a inesperada visita de uma garota! Bulma lhe propõe uma parceria para buscar as sete Esferas do Dragão, que, quando reunidas, são capazes de realizar qualquer desejo! Perigos e adversários não faltarão no caminho dessa dupla inusitada, e os mais variados personagens marcarão presença nesta aventura cheia de humor!', 'preco' => 89, 'imagem' => 'dragon_ball_1.jpg', 'link_compra' => '../compra/dragonballZ_vol01.php'],
  30 => ['categoria_id' => 1, 'nome' => 'Dragon Ball - 02', 'autor' => 'Akira Toriyama', 'ano_publicacao' => 2021, 'paginas' => 192, 'isbn' => 'Edição impressa — ISBN específico da tiragem', 'editora' => 'Panini', 'descricao' => 'Depois de passar tantos apuros, Goku, Bulma e seus companheiros seguem sua jornada e já conseguiram cinco das sete Esferas do Dragão!A sexta esfera já foi localizada, mas precisarão novamente da ajuda do Mestre Kame! E logo eles descobrirão também que há outros interessados na dádiva do Rei Dragão Sheng Long.', 'preco' => 24.50, 'imagem' => 'dragon_ball_2.jpg', 'link_compra' => '../compra/dragonballZ_vol02.php'],
  31 => ['categoria_id' => 1, 'nome' => 'Dragon Ball - 03', 'autor' => 'Akira Toriyama', 'ano_publicacao' => 2021, 'paginas' => 192, 'isbn' => 'Edição impressa — ISBN específico da tiragem', 'editora' => 'Panini', 'descricao' => 'O Trunks do futuro surge novamente! Em seu mundo, um homem muito parecido com o Goku, chamado de Goku Black, está tentando acabar com a humanidade. Para ajudar Trunks, Goku e Vegeta vão ao futuro. Enquanto isso, Zamasu, o candidato a próximo kaiohshin do Décimo Universo, está de olho nos passos de Goku.', 'preco' => 44.90, 'imagem' => 'dragon_ball_3.jpg', 'link_compra' => '../compra/dragonballZ_vol03.php'],
  32 => ['categoria_id' => 1, 'nome' => 'Dragon Ball - 04', 'autor' => 'Akira Toriyama', 'ano_publicacao' => 2021, 'paginas' => 192, 'isbn' => 'Edição impressa — ISBN específico da tiragem', 'editora' => 'Panini', 'descricao' => 'Após um intenso treinamento com Mestre Kame, Goku e Kuririn participam do grande Torneio de Artes Marciais, onde enfrentam alguns dos lutadores mais fortes do mundo. Enquanto a competição chega à sua emocionante reta final, um misterioso guerreiro chamado Jackie Chun surge como o maior desafio da dupla. Depois do torneio, uma nova aventura começa quando Goku parte novamente em busca das Esferas do Dragão e cruza o caminho do poderoso Exército Red Ribbon, uma organização militar disposta a fazer qualquer coisa para conquistar seu objetivo.', 'preco' => 54.90, 'imagem' => 'dragon_ball_4.jpg', 'link_compra' => '../compra/dragonballZ_vol04.php'],
  33 => ['categoria_id' => 1, 'nome' => 'Naruto, Vol. 72', 'autor' => 'Masashi Kishimoto', 'ano_publicacao' => 2021, 'paginas' => 192, 'isbn' => 'Edição impressa — ISBN específico da tiragem', 'editora' => 'Panini', 'descricao' => 'Kaguya foi selada com sucesso, mas, quando o conflito caminha para a sua conclusão, Sasuke se rebela! 
        Insistindo em sentimentos incompatíveis, Naruto e Sasuke se encaram apostando tudo, e as cortinas da batalha entre os dois heróis se abrem!!', 'preco' => 157.68, 'imagem' => 'naruto_vol72.jpg', 'link_compra' => '../compra/naruto_vol72.php'],
  34 => ['categoria_id' => 1, 'nome' => 'Naruto, Vol. 71: Eu Amo Vocês', 'autor' => 'Masashi Kishimoto', 'ano_publicacao' => 2021, 'paginas' => 192, 'isbn' => 'Edição impressa — ISBN específico da tiragem', 'editora' => 'Panini', 'descricao' => 'O Tsukuyomi Infinito é ativado e as pessoas são aprisionadas no mundo dos sonhos. Kaguya, que voltou à vida graças a Zetsu Negro, 
        começa a agir para tornar todos os chakras um só!! Naruto e Sasuke utilizam os poderes que receberam de Rikudou Sennin para tentar selá-la!!', 'preco' => 69.90, 'imagem' => 'naruto_vol71.jpg', 'link_compra' => '../compra/naruto_vol71.php'],
  35 => ['categoria_id' => 1, 'nome' => 'Naruto, Vol. 69', 'autor' => 'Masashi Kishimoto', 'ano_publicacao' => 2021, 'paginas' => 192, 'isbn' => 'Edição impressa — ISBN específico da tiragem', 'editora' => 'Panini', 'descricao' => 'Com o Rinnetensei no Jutsu, Madara ressuscita! Naruto e as Bijuus resistem, mas Madara recupera o Rinnegan do Zetsu Branco.
         O Gedou Mazou é invocado novamente e captura as Bijuus, e Kurama é extraída de dentro de Naruto?!', 'preco' => 100, 'imagem' => 'naruto_vol69.jpg', 'link_compra' => '../compra/naruto_vol69.php'],
  36 => ['categoria_id' => 1, 'nome' => 'Naruto, Vol. 70', 'autor' => 'Masashi Kishimoto', 'ano_publicacao' => 2021, 'paginas' => 192, 'isbn' => 'Edição impressa — ISBN específico da tiragem', 'editora' => 'Panini', 'descricao' => 'A fim de deter Madara, Gai libera a técnica dos Oito Portais Internos, que lhe fornece uma força física inimaginável, mas a um preço altíssimo…
         Enquanto isso, Naruto, inconsciente, encontra-se com o lendário eremita Rikudou Sennin, que revelará as verdadeiras origens do jovem shinobi e da
          guerra que está assolando o mundo!', 'preco' => 79, 'imagem' => 'naruto_vol70.webp', 'link_compra' => '../compra/naruto_vol70.php'],
  37 => ['categoria_id' => 1, 'nome' => 'Naruto Gold - Vol. 1', 'autor' => 'Masashi Kishimoto', 'ano_publicacao' => 2025, 'paginas' => 192, 'isbn' => '9788542602418', 'editora' => 'Panini', 'descricao' => 'Esta é a Vila Oculta da Folha. Naruto é o garoto mais problemático da Academia Ninja e está sempre aprontando todas!! Seu grande sonho é se tornar um shinobi 
       digno do título de Hokage, o mais forte e respeitado ninja da vila, e superar todos os Hokages anteriores...!! 
       Mas um segredo em torno de seu nascimento o mantém distante tanto de seu sonho quanto das pessoas...!! Não perca mais uma chance de acompanhar a 
       empolgante jornada de Naruto, o garoto ninja que conquistou o mundo inteiro, nesta nova edição de luxo com pôsteres, freetalks exclusivos do autor e muito mais!', 'preco' => 38.63, 'imagem' => 'narutogold_01.jpg', 'link_compra' => '../compra/naruto_gold_vol01.php'],
  38 => ['categoria_id' => 1, 'nome' => 'Naruto Gold - Vol. 2', 'autor' => 'Masashi Kishimoto', 'ano_publicacao' => 2025, 'paginas' => 208, 'isbn' => '9788542602609', 'editora' => 'Panini', 'descricao' => 'Naruto, Sasuke e Sakura são testados por Kakashi-sensei!! Se passarem nessa difícil prova, eles se tornarão Genins – ninjas aprendizes! 
        A Equipe Sete parte para assegurar a proteção de um notável construtor de pontes, o senhor Tazuna, mas sinistras sombras assassinas os espreitam!', 'preco' => 48.20, 'imagem' => 'narutogold_02.jpg', 'link_compra' => '../compra/naruto_gold_vol02.php'],
  39 => ['categoria_id' => 1, 'nome' => 'Naruto Gold - Vol. 3', 'autor' => 'Masashi Kishimoto', 'ano_publicacao' => 2023, 'paginas' => 208, 'isbn' => '9788542602623', 'editora' => 'Panini', 'descricao' => 'Zabuza, o demônio que deveria ter sido liquidado pelo sharingan de Kakashi, está vivo! Naruto e seus companheiros, que foram ao País das Ondas escoltando Tazuna, 
        são acometidos por uma imensa sensação de insegurança. Mas não é hora para fraquejar! Sob a supervisão de Kakashi-sensei, um intenso treinamento tem início!', 'preco' => 32.90, 'imagem' => 'narutogold_vol3.jpg', 'link_compra' => '../compra/naruto_gold_vol03.php'],
  40 => ['categoria_id' => 1, 'nome' => 'Naruto Gold - Vol. 4', 'autor' => 'Masashi Kishimoto', 'ano_publicacao' => 2023, 'paginas' => 208, 'isbn' => '9788542602838', 'editora' => 'Panini', 'descricao' => 'Sasuke desmaia ao proteger Naruto...!! Nesse momento, o garoto, tomado por ira e tristeza, sofre uma transformação. O que vai ser de Haku, 
        atingido pelo punho enfurecido de Naruto...?! E que rumo tomará o combate entre Zabuza e Kakashi?! O “arco do País das Ondas” chega a um fim turbulento!!', 'preco' => 42.90, 'imagem' => 'narutogold_04.jpg', 'link_compra' => '../compra/naruto_gold_vol04.php'],
  41 => ['categoria_id' => 1, 'nome' => 'One Piece Vol.67', 'autor' => 'Eiichiro Oda', 'ano_publicacao' => 2021, 'paginas' => 192, 'isbn' => 'Edição impressa — ISBN específico da tiragem', 'editora' => 'Panini', 'descricao' => 'Luffy e seu bando atendem a um chamado de socorro e caem em uma ilha proibida chamada Punk Hazard! Depois de encontrar um dragão logo de cara, 
        eles terão de descobrir onde está o dono das pernas falantes que estavam grudadas no monstro!', 'preco' => 66.90, 'imagem' => 'one_piece_67.jpg', 'link_compra' => '../compra/onepiece_VOL67.php'],
  42 => ['categoria_id' => 1, 'nome' => 'One Piece Vol.66', 'autor' => 'Eiichiro Oda', 'ano_publicacao' => 2017, 'paginas' => 208, 'isbn' => '9788542605938', 'editora' => 'Panini', 'descricao' => 'Vander Decken não se conformou com a rejeição da princesa Shirahoshi e usou seus poderes para lançar a arca lendária Noah contra o Reino Ryuugu! 
        Com o país prestes a ser destruído, Luffy decide destruir essa importante embarcação, mas algo se coloca em seu caminho!', 'preco' => 100, 'imagem' => 'onepiece_vol66.jpg', 'link_compra' => '../compra/onepiece_vol66.php'],
  43 => ['categoria_id' => 1, 'nome' => 'One Piece Vol.64', 'autor' => 'Eiichiro Oda', 'ano_publicacao' => 2021, 'paginas' => 192, 'isbn' => 'Edição impressa — ISBN específico da tiragem', 'editora' => 'Panini', 'descricao' => 'Hody Jones domina o palácio real e anuncia a sua intenção de destruir o Reino Ryuugu! 
        É revelado o verdadeiro responsável pelo assassinato da rainha Otohime e o Bando do Chapéu de Palha não ficará de braços cruzados!', 'preco' => 53.91, 'imagem' => 'onepiece_vol64.jpg', 'link_compra' => '../compra/onepiece_vol64.php'],
  44 => ['categoria_id' => 1, 'nome' => 'One Piece Vol.65', 'autor' => 'Eiichiro Oda', 'ano_publicacao' => 2021, 'paginas' => 192, 'isbn' => 'Edição impressa — ISBN específico da tiragem', 'editora' => 'Panini', 'descricao' => 'Vander Decken, obcecado por Shirahoshi, decide destruir o Reino Ryuugu! E, 
        enquanto o Bando do Chapéu de Palha procura uma forma de evitar essa calamidade, o combate contra Hody Jones se acirra e suas verdadeiras motivações são reveladas!', 'preco' => 55, 'imagem' => 'onepiece_vol65.jpg', 'link_compra' => '../compra/onepiece_vol65.php'],
  45 => ['categoria_id' => 1, 'nome' => 'One Piece Vol.1', 'autor' => 'Eiichiro Oda', 'ano_publicacao' => 2024, 'paginas' => 192, 'isbn' => '9788573516975', 'editora' => 'Panini', 'descricao' => 'A tripulação pirata mais famosa dos quadrinhos finalmente joga sua âncora de novo no Brasil! Com roteiro e arte de Eiichiro Oda, 
        o mangá de maior sucesso de todos os tempos retorna ao país, agora sob a bandeira Planet Mangá, da Panini Comics! Para ser o rei dos piratas,
         Luffy, o homem-borracha, precisa reunir uma tripulação e encontrar o maior de todos os tesouros. No caminho, enfrentará a Marinha, monstros, e
          muitos outros piratas que têm o mesmo objetivo. Então prepare-se pra encarar os perigos dos mares. A maior aventura de todas vai recomeçar!', 'preco' => 34.90, 'imagem' => 'onepiece_vol1.jpg', 'link_compra' => '../compra/onepiece_vol01.php'],
  46 => ['categoria_id' => 1, 'nome' => 'One Piece Vol.2', 'autor' => 'Eiichiro Oda', 'ano_publicacao' => 2021, 'paginas' => 192, 'isbn' => 'Edição impressa — ISBN específico da tiragem', 'editora' => 'Panini', 'descricao' => 'Luffy Chapéu de Palha não está mais sozinho em sua jornada, depois de admitir em sua tripulação o famoso espadachim Roronoa Zoro, 
        o Caça-Piratas! Mas um imprevisto os separa, colocando Luffy no caminho do Bando do Pirata Buggy, o Palhaço, que está aterrorizando 
        uma pequena cidade portuária! E ele também conhece uma misteriosa ladra, que promete muita confusão e trapaças por onde passa!', 'preco' => 27.24, 'imagem' => 'onepiece_vol2.jpg', 'link_compra' => '../compra/onepiece_vol02.php'],
  47 => ['categoria_id' => 1, 'nome' => 'One Piece Vol.3', 'autor' => 'Eiichiro Oda', 'ano_publicacao' => 2021, 'paginas' => 192, 'isbn' => 'Edição impressa — ISBN específico da tiragem', 'editora' => 'Panini', 'descricao' => 'O Pirata Buggy revela o que o torna tão temido e conta ao Luffy a sua época de juventude ao lado de Shanks! E a Nami? 
        Será que Luffy e Zoro conseguirão convencê-la a se tornar a navegadora deles?', 'preco' => 31.40, 'imagem' => 'onepiece_vol3.jpg', 'link_compra' => '../compra/onepiece_vol03.php'],
  48 => ['categoria_id' => 1, 'nome' => 'One Piece Vol.4', 'autor' => 'Eiichiro Oda', 'ano_publicacao' => 2024, 'paginas' => 312, 'isbn' => '9788573519037', 'editora' => 'Panini', 'descricao' => 'Luffy e seus companheiros chegam à vila de Usopp em busca de um novo navio. Mas, por um acaso, eles descobrem as terríveis 
        intenções de um perigoso ex-capitão pirata disfarçado de mordomo!', 'preco' => 31.40, 'imagem' => 'onepiece_vol4.jpg', 'link_compra' => '../compra/onepiece_vol04.php'],
  49 => ['categoria_id' => 1, 'nome' => 'Tokyo ghoul: re vol. 16', 'autor' => 'Sui Ishida', 'ano_publicacao' => 2021, 'paginas' => 192, 'isbn' => 'Edição impressa — ISBN específico da tiragem', 'editora' => 'Panini', 'descricao' => '“Não quero mais ficar sem fazer nada.” O processo de ghoulificação da humanidade avança em Tokyo. Para eliminar a origem da “toxina”, o CCG e os ghouls unem forças e Kaneki e Ayato vão para o subterrâneo do Distrito 24. Quem os espera lá é Nimura Furuta. O que Kaneki deseja ao ver diante de seus olhos a “causa” de ter se tornado um ghoul? E qual será o destino de Tokyo e dos ghouls', 'preco' => 35.90, 'imagem' => 'tokyoghoul_vol16.jpg', 'link_compra' => '../compra/tokyoghoul_16.php'],
  50 => ['categoria_id' => 1, 'nome' => 'Tokyo ghoul: re vol. 15', 'autor' => 'Sui Ishida', 'ano_publicacao' => 2021, 'paginas' => 192, 'isbn' => 'Edição impressa — ISBN específico da tiragem', 'editora' => 'Panini', 'descricao' => '“Você comeu todas elas. Por isso estou aqui.” Para salvar Ken Kaneki e Tokyo, os ghouls e o CCG decidiram unir forças. Do esforço conjunto de todos aqueles que vivem em Tokyo, finalmente encontraram, no gigantesco corpo que soterrou todo o Distrito 23, uma pista do corpo dele. Tooru Mutsuki, que busca a miragem de “Haise Sasaki” e Touka Kirishima, que tenta salvar “Ken Kaneki”. Tem início a última batalha que questiona a existência da Equipe Quinx. E na mente de Kaneki, surge “aquela mulher” que ama ler e comer!', 'preco' => 35.90, 'imagem' => 'tokyoghoul_vol15.jpg', 'link_compra' => '../compra/tokyoghoul_15.php'],
  51 => ['categoria_id' => 1, 'nome' => 'Tokyo ghoul: re vol. 14', 'autor' => 'Sui Ishida', 'ano_publicacao' => 2021, 'paginas' => 192, 'isbn' => 'Edição impressa — ISBN específico da tiragem', 'editora' => 'Panini', 'descricao' => 'O confronto entre o CCG e os ghouls da cafeteria Anteiku se acirra, com muitas perdas em ambos os lados. E, afinal, quem é a verdadeira "Coruja de um olho só"? Quem sobreviverá a esta noite tão terrível? Tokyo Ghoul chega ao fim, mas não percam a continuação da história em Tokyo Ghoul: re.', 'preco' => 47.90, 'imagem' => 'tokyoghoul_vol14.jpg', 'link_compra' => '../compra/tokyoghoul_14.php'],
  52 => ['categoria_id' => 1, 'nome' => 'Tokyo ghoul: re vol. 13', 'autor' => 'Sui Ishida', 'ano_publicacao' => 2021, 'paginas' => 192, 'isbn' => 'Edição impressa — ISBN específico da tiragem', 'editora' => 'Panini', 'descricao' => 'O CCG descobre uma pista sobre o paradeiro do temido ghoul "Coruja", que leva direto à Anteiku! Yoshimura tenta distrair os agentes durante o ataque, enquanto o restante dos funcionários e amigos corre contra o tempo para fugir em segurança! E qual será o papel de Kaneki em meio a esse confronto?', 'preco' => 47.90, 'imagem' => 'tokyoghoul_vol13.jpg', 'link_compra' => '../compra/tokyoghoul_13.php'],
  53 => ['categoria_id' => 1, 'nome' => 'Tokyo Ghoul, Vol. 1', 'autor' => 'Sui Ishida', 'ano_publicacao' => 2015, 'paginas' => 224, 'isbn' => '9788542601589', 'editora' => 'Panini', 'descricao' => 'Os ghouls vivem entre nós, iguais às pessoas normais em todos os aspectos — exceto pela sua sede por carne humana. Ken Kaneki é um estudante universitário comum até que um encontro violento o transforma no primeiro híbrido meio humano, meio ghoul. Preso entre dois mundos, ele precisa sobreviver às guerras territoriais entre ghouls, aprender mais sobre a sociedade ghoul e dominar seus novos poderes.   
O tímido Ken Kaneki está animado para sair em um encontro com a bela Rize. Mas descobre que ela está interessada apenas em seu corpo — em devorá-lo, para ser mais preciso. Quando um resgate moralmente questionável o transforma no primeiro híbrido meio humano, meio ghoul, Ken é arrastado para o mundo sombrio e violento dos ghouls, que existe paralelamente ao nosso.', 'preco' => 79.23, 'imagem' => 'tokyoghoul_vol1.jpg', 'link_compra' => '../compra/tokyoghoul_1.php'],
  54 => ['categoria_id' => 1, 'nome' => 'Tokyo Ghoul, Vol. 2', 'autor' => 'Sui Ishida', 'ano_publicacao' => 2021, 'paginas' => 192, 'isbn' => 'Edição impressa — ISBN específico da tiragem', 'editora' => 'Panini', 'descricao' => 'Além de ter que aceitar sua nova condição como um meio Ghoul, Kaneki precisa aprender com os membros da Anteiku a se comportar como um deles para continuar vivendo entre os humanos. Porém, os recentes eventos ocorridos no Distrito 20 atraem investigadores ao local, e eles não demonstram ter tempo ou disposição para discernir o caráter de seus alvos.', 'preco' => 47.90, 'imagem' => 'tokyoghoul_vol2.jpg', 'link_compra' => '../compra/tokyoghoul_2.php'],
  55 => ['categoria_id' => 1, 'nome' => 'Tokyo Ghoul, Vol. 3', 'autor' => 'Sui Ishida', 'ano_publicacao' => 2021, 'paginas' => 192, 'isbn' => 'Edição impressa — ISBN específico da tiragem', 'editora' => 'Panini', 'descricao' => 'Kaneki e Touka se arriscam cada vez mais para proteger a Hinami, que está sendo caçada pelos agentes do Comitê Contra Ghouls. E isso colocará Kaneki mais uma vez em uma encruzilhada contra seus novos instintos como um ghoul.', 'preco' => 33.90, 'imagem' => 'tokyoghoul_vol3.jpg', 'link_compra' => '../compra/tokyoghoul_3.php'],
  56 => ['categoria_id' => 1, 'nome' => 'Tokyo Ghoul, Vol. 4', 'autor' => 'Sui Ishida', 'ano_publicacao' => 2021, 'paginas' => 192, 'isbn' => 'Edição impressa — ISBN específico da tiragem', 'editora' => 'Panini', 'descricao' => 'Seis meses se passaram após a operação “Limpa-leilão”. Shu Tsukiyama está em um vórtice de sofrimento e, para ajudá-lo, Kanae von Rosewald e a família Tsukiyama realizam novamente um sequestro em massa que chamam de “colheita”. Porém, ao ver que seu mestre não se recupera, Kanae começa a agir por conta própria e pede a ajuda da fotógrafa Chie Hori.Enquanto isso, Haise e a Equipe Quinx são promovidos, e seu próximo alvo é o ghoul “Rose”.Qual é a relação entre essas pessoas e “Ken Kaneki”?', 'preco' => 35.90, 'imagem' => 'tokyoghoul_vol4.jpg', 'link_compra' => '../compra/tokyoghoul_4.php'],
  57 => ['categoria_id' => 1, 'nome' => 'Vinland saga vol. 29', 'autor' => 'Makoto Yukimura', 'ano_publicacao' => 2021, 'paginas' => 192, 'isbn' => 'Edição impressa — ISBN específico da tiragem', 'editora' => 'Panini', 'descricao' => 'Enquanto Thorfinn e seus companheiros cultivam campos de trigo e constroem vínculos amistosos com o povo Ulnoo, uma praga se espalha por Vinland. Desconfiança e ódio crescem, fazendo com que os nativos planejem um confronto para proteger a própria paz. Thorfinn busca negociar para refrear as hostilidades, porém, certo evento acaba instigando aqueles que são a favor da violência, e a aldeia de Arneis arde em chamas. O que acontecerá com o sonho de Thorfinn? O épico nórdico que questiona o verdadeiro significado de ser um guerreiro finalmente chega ao fim.', 'preco' => 35.74, 'imagem' => 'vinland_saga_vol29.png', 'link_compra' => '../compra/vinland_saga_vol29.php'],
  58 => ['categoria_id' => 1, 'nome' => 'Vinland saga vol. 28', 'autor' => 'Makoto Yukimura', 'ano_publicacao' => 2021, 'paginas' => 192, 'isbn' => 'Edição impressa — ISBN específico da tiragem', 'editora' => 'Panini', 'descricao' => 'Enquanto Thorfinn e os outros desbravam Vinland, nativos da tribo Ulnoo surgem diante deles, deixando o grupo de aldeões do vilarejo Arneis abalado. Thorfinn quer formar laços de amizade com os Ulnoo, mas algumas pessoas, como Ivar, estão céticas em relação à interação com os indígenas. Para piorar, Ivar trouxe consigo uma “espada”, algo proibido. Enquanto isso, Misqe’g Pi’gw, o ancião da tribo Ulnoo, realiza um ritual que prediz um futuro de destruição trazido por Thorfinn e os outros nórdicos.Tanto Thorfinn e seus amigos, o povo nórdico, quanto o povo Ulnoo não estão unidos entre si.Em uma tentativa de dissipar a insegurança, Hild trama um plano de assassinato e a situação nos arredores do vilarejo Arneis fica bem complicada.', 'preco' => 31.40, 'imagem' => 'vinland_saga_vol28.png', 'link_compra' => '../compra/vinland_saga_vol28.php'],
  59 => ['categoria_id' => 1, 'nome' => 'Vinland saga vol. 27', 'autor' => 'Makoto Yukimura', 'ano_publicacao' => 2021, 'paginas' => 192, 'isbn' => 'Edição impressa — ISBN específico da tiragem', 'editora' => 'Panini', 'descricao' => 'Após finalmente chegar à prometida Vinland, Thorfinn, que está dando tudo de si para o desenvolvimento do vilarejo Arneis se vê diante dos nativos. O rapaz deseja criar laços de amizade com o povo Ulnoo, no entanto, Ivar se sente pessimista diante dessa situação. Nesse meio-tempo, Misqeg Pigw realiza um ritual para ver o futuro, que o revela a destruição que Thorfinn e os nórdicos trarão à terra. Além disso, Gudrid revela que está grávida e Hild finalmente decide deixar seu ódio para trás a fim de perdoar Thorfinn. Com grandes esperanças e um punhado de ansiedade, a plantação de trigo de Vinland cintila intensamente.', 'preco' => 31.58, 'imagem' => 'vinland_saga_vol27.png', 'link_compra' => '../compra/vinland_saga_vol27.php'],
  60 => ['categoria_id' => 1, 'nome' => 'Vinland saga vol. 26', 'autor' => 'Makoto Yukimura', 'ano_publicacao' => 2021, 'paginas' => 192, 'isbn' => 'Edição impressa — ISBN específico da tiragem', 'editora' => 'Panini', 'descricao' => 'Após o sucesso da Expedição a Vinland, Thorfinn e sua tripulação são agora os habitantes originais da vila de Arneis. Essas terras exuberantes são um refúgio de paz, mas algumas ainda carregam as cicatrizes da guerra. Embora a conquista do Oeste comece, o encontro com os nativos não parece apaziguar os conflitos.', 'preco' => 38.90, 'imagem' => 'vinland_saga_vol26.png', 'link_compra' => '../compra/vinland_saga_vol26.php'],
  61 => ['categoria_id' => 1, 'nome' => 'Vinland Saga Deluxe Vol. 1', 'autor' => 'Makoto Yukimura', 'ano_publicacao' => 2021, 'paginas' => 192, 'isbn' => 'Edição impressa — ISBN específico da tiragem', 'editora' => 'Panini', 'descricao' => 'Quando criança, Thorfinn, filho do lendário guerreiro viking Thors, vive sem saber o passado do pai, que descobriu após anos no campo de batalha algo mais valioso do que matar seus iguais, viver sua vida de paz. Ao saber os tempos de guerra de seu pai, o garoto se revolta e vai à guerra com ele, mas acaba sendo tarde demais quando reconhece o valor dele. No passado, Thors se viu obrigado a lutar na guerra entre Dinamarca e Inglaterra junto aos Jomsvikings.', 'preco' => 41.20, 'imagem' => 'vinland_saga_vol1.png', 'link_compra' => '../compra/vinland_saga_vol1.php'],
  62 => ['categoria_id' => 1, 'nome' => 'Vinland Saga Deluxe Vol. 2', 'autor' => 'Makoto Yukimura', 'ano_publicacao' => 2021, 'paginas' => 192, 'isbn' => 'Edição impressa — ISBN específico da tiragem', 'editora' => 'Panini', 'descricao' => 'Após a emboscada que culminou na morte de seu pai, Thorfinn seguiu viagem pela Inglaterra sob ordens de Askeladd. E uma batalha na ponte de Londres mostrará ao jovem guerreiro que os próximos duelos poderão ser muito mais difíceis do que imaginava. O bando de mercenários dinamarqueses de Askeladd planeja uma investida contra o exército de Thorkell para resgatar o princípe Knut. Para isso, eles entram em um condado do País de Gales, onde buscam refúgio. Lá, Askeladd se encontra com um antigo companheiro de batalha.', 'preco' => 40.60, 'imagem' => 'vinland-saga-deluxe-vol-2.webp', 'link_compra' => '../compra/vinland_saga_vol2.php'],
  63 => ['categoria_id' => 1, 'nome' => 'Vinland Saga Deluxe Vol. 3', 'autor' => 'Makoto Yukimura', 'ano_publicacao' => 2021, 'paginas' => 192, 'isbn' => 'Edição impressa — ISBN específico da tiragem', 'editora' => 'Panini', 'descricao' => 'Tramando uma estratégia contra os dinamarqueses, Askeladd sequestra o príncipe Knut e foge da perseguição do bando de Thorkell. No entanto, em sua própria tropa começam a surgir dúvidas a respeito de suas intenções e de sua capacidade. Enquanto isso, Thorfinn continua a sua luta decisiva contra Thorkell, que decide contar para o jovem um pouco mais sobre seu pai.', 'preco' => 52.50, 'imagem' => 'vinland_saga_vol3.png', 'link_compra' => '../compra/vinland_saga_vol3.php'],
  64 => ['categoria_id' => 1, 'nome' => 'Vinland Saga Deluxe Vol. 4', 'autor' => 'Makoto Yukimura', 'ano_publicacao' => 2021, 'paginas' => 192, 'isbn' => 'Edição impressa — ISBN específico da tiragem', 'editora' => 'Panini', 'descricao' => 'Luffy e seu bando atendem a um chamado de socorro e caem em uma ilha proibida chamada Punk Hazard! Depois de encontrar um dragão logo de cara, 
        eles terão de descobrir onde está o dono das pernas falantes que estavam grudadas no monstro!', 'preco' => 57.90, 'imagem' => 'vinland_saga_vol4.png', 'link_compra' => '../compra/vinland_saga_vol4.php'],
  65 => ['categoria_id' => 2, 'nome' => 'Anos 2000: O Renascimento Da Marvel Vol. 04 (de 10) - Capitão América', 'autor' => 'Ed Brubaker, Steve Epting e equipe Marvel', 'ano_publicacao' => 2025, 'paginas' => 160, 'isbn' => '9786525937007', 'editora' => 'Panini', 'descricao' => 'O Capitão América é a espinha dorsal do Universo Marvel, a quem todos os outros super-herói recorrem quando estão em dúvida. Mas o que acontece quando é a própria Sentinela da Liberdade quem nutre dúvidas em seu coração? A resposta está em duas histórias muito cultuadas estreladas por Steve Rogers, que, depois de enfrentar terroristas, deve lutar contra o Soldado Invernal.

Mergulhe nos quadrinhos da Marvel dos anos 2000 e descubra o renascimento da Casa das Ideias!', 'preco' => 39.90, 'imagem' => 'capitao_1.webp', 'link_compra' => '../compra/capitao_1.php'],
  66 => ['categoria_id' => 2, 'nome' => 'Capitão América Por Mark Waid E Chris Samnee', 'autor' => 'Mark Waid, Chris Samnee, Leonardo Romero', 'ano_publicacao' => 2024, 'paginas' => 248, 'isbn' => '9786525929873', 'editora' => 'Panini', 'descricao' => 'Mark Waid e Chris Samnee, a equipe espetacular que transformou o mundo do Demolidor e já produziu um thriller inesquecível estrelando a Viúva Negra, se reúnem para dar a vez ao maior herói de todos – o Capitão América! Steve Rogers está de volta à ação, e com escudo em mãos ele sai numa jornada através dos Estados Unidos para restaurar a sua reputação. Mas os perigos com os quais o herói vai se deparar são diferentes de tudo que ele já viu, e vão demandar muita coragem! E quando ele encontrar o mais novo Espadachim, vai se ver diante de um duelo inacreditável!', 'preco' => 109.90, 'imagem' => 'capitao_2.webp', 'link_compra' => '../compra/capitao_2.php'],
  67 => ['categoria_id' => 2, 'nome' => 'Capitão América E Os Vingadores 01', 'autor' => 'Chip Zdarsky, Valerio Schiti', 'ano_publicacao' => 2026, 'paginas' => 56, 'isbn' => 'Não se aplica — revista periódica', 'editora' => 'Panini', 'descricao' => 'UMA NOVA ERA PARA O CAPITÃO AMÉRICA COMEÇA AQUI! Uma nova revista mensal para o herói que celebra 85 anos de criação!

O futuro do Capitão e dos Vingadores começa a ser traçado aqui. Enquanto a Sentinela da Liberdade dormia no gelo, o mundo mudou… para melhor e para pior. Steve Rogers desperta para uma realidade onde as batalhas são travadas nas sombras, através de segredos e subterfúgios, e os vilões não são tão fáceis de identificar. 

Quando um ditador em ascensão chamado Victor Von Doom conquista a Latvéria, Steve enfrenta uma decisão crucial: adaptar-se a um novo tipo de guerra ou trilhar seu próprio caminho? E o que a escolha que ele fez no passado significará para o seu futuro? Vivencie a história inédita do primeiro encontro do Capitão América com o Doutor Destino, enquanto os autores Chip Zdarsky e Valerio Schiti unem forças para uma nova era revolucionária do Capitão América! Esta é a Latvéria como você nunca viu antes…', 'preco' => 14.90, 'imagem' => 'capitao_3.webp', 'link_compra' => '../compra/capitao_3.php'],
  68 => ['categoria_id' => 2, 'nome' => 'Coleção Clássica Marvel: Nova Fase Vol. 17 - Capitão América 6 - Se O Passado Não Estiver Morto!', 'autor' => 'Stan Lee, Jack Kirby', 'ano_publicacao' => 2026, 'paginas' => 128, 'isbn' => 'Não se aplica — revista periódica', 'editora' => 'Panini', 'descricao' => 'Nesta edição, a origem do Capitão América! Steve relembra ao Nick Fury seus primeiros dias como heróis com ele e Buck enfrentando nazistas na Segunda Guerra Mundial!

E mais: o herói enfrenta Batroc! E quando um grupo de espiões rouba os planos da SHIELD de um protótipo de nova geração de vida artificial, o Capitão América entra em ação para recuperá-los!', 'preco' => 39.90, 'imagem' => 'capitao_4.webp', 'link_compra' => '../compra/capitao_4.php'],
  69 => ['categoria_id' => 2, 'nome' => 'Doutor Estranho De Asgard', 'autor' => 'Derek Landy, Carlos Magno', 'ano_publicacao' => 2026, 'paginas' => 120, 'isbn' => 'Não se aplica — revista periódica', 'editora' => 'Panini', 'descricao' => 'No clímax épico da Caçada Sangrenta, o Doutor Destino enganou o Doutor Estranho para que ele renunciasse ao título de Mago Supremo. Agora, Destino está governando o mundo e Stephen Strange está… passando por uma crise de identidade. Em busca de um propósito, ele viaja para Asgard para ver se o reino de Thor está procurando por um Mago Supremo. Loki está disposto a ajudar, mas essa ajuda vem com uma condição perversa, e Strange logo percebe que se tornar a maior autoridade mágica de Asgard será mais complicado do que ele imaginava!', 'preco' => 39.90, 'imagem' => 'doutor_1.jpg', 'link_compra' => '../compra/doutor_1.php'],
  70 => ['categoria_id' => 2, 'nome' => 'Doutor Estranho (2024) 01', 'autor' => 'Jed MacKay, Pasqual Ferry, Andy MacDonald', 'ano_publicacao' => 2024, 'paginas' => 136, 'isbn' => 'Não se aplica — revista periódica', 'editora' => 'Panini', 'descricao' => 'STEPHEN STRANGE ESTÁ DE VOLTA! Depois do tão esperado reencontro do Doutor Estranho com Clea e Wong, a rotina do Mago Supremo volta aos eixos. Quando uma misteriosa e interminável doença do sono afeta as crianças da rua Bleecker, só pode haver um culpado. Strange e Clea precisam adentrar a Dimensão dos Sonhos para confrontar seu antigo inimigo, Pesadelo. Em seguida, um culto invoca o terrível Dormammu direto para as ruas de Nova York, e o Mago Supremo vai precisar arriscar tudo para derrotá-lo! Para além disso, Wong e Pandora Peters estão trabalhando juntos para reconfigurar a VARINHA, e sua primeira missão já será horripilante! Por fim, Strange e Clea são convidados para um casamento interdimensional em que os convidados estão sendo misteriosamente assassinados!', 'preco' => 39.90, 'imagem' => 'doutor_2.jpg', 'link_compra' => '../compra/doutor_2.php'],
  71 => ['categoria_id' => 2, 'nome' => 'Doutor Estranho: Princípio E Fim', 'autor' => 'J. Michael Straczynski, Samm Barnes, Brandon Peterson', 'ano_publicacao' => 2024, 'paginas' => 152, 'isbn' => '9786525929330', 'editora' => 'Panini', 'descricao' => 'O jovem e arrogante cirurgião chamado Dr. Stephen Strange está prestes a colidir com seu destino. Uma jornada que o forçará a explorar as profundezas de seu próprio coração… e os pontos mais distantes do universo! Mestres das histórias em quadrinhos, J. Michael Straczynski, Samm Barnes e Brandon Peterson narram uma nova abordagem da origem do mestre das artes místicas do Universo Marvel!', 'preco' => 69.90, 'imagem' => 'doutor_3.jpg', 'link_compra' => '../compra/doutor_3.php'],
  72 => ['categoria_id' => 2, 'nome' => 'Doutor Estranho (2023) 01', 'autor' => 'Jed MacKay, Marcelo Ferreira', 'ano_publicacao' => 2023, 'paginas' => 128, 'isbn' => 'Não se aplica — revista periódica', 'editora' => 'Panini', 'descricao' => 'O Doutor Estranho está morto! E um novo Mago Supremo assumiu seu lugar - ou deveríamos dizer Maga? Assombrada por suas memórias recém-recuperadas, Clea quer mais que tudo trazer de volta Stephen Strange. Mas quando uma ameaça surge na forma de um misterioso grupo, Clea precisa cumprir seus novos deveres como Maga Suprema, pois é a única e última frente de defesa da Terra contra ataques mágicos. Para além disso, terríveis e cruéis caçadores de monstros, inimigos des-mortos, reuniões familiares inesperadas... Clea pode estar prestes descobrir que sua nova função não deixa muito tempo para seus interesses e vida pessoal.', 'preco' => 34.90, 'imagem' => 'doutor_4.jpg', 'link_compra' => '../compra/doutor_4.php'],
  73 => ['categoria_id' => 2, 'nome' => 'Hulk: A Tempestade (Marvel Essenciais)', 'autor' => 'Peter David, Lee Weeks', 'ano_publicacao' => 2025, 'paginas' => 160, 'isbn' => '9786525939216', 'editora' => 'Panini', 'descricao' => 'Espreitando nas profundezas do oceano, além de tubarões a lulas gigantes, está o Hulk. Quando um episódio há muito enterrado da juventude de Bruce Banner começa a emergir com possíveis ramificações para o futuro, o Hulk se vê levado para uma ilha estranha, povoada por várias vítimas infelizes... e alguns monstros inesperados.', 'preco' => 86.90, 'imagem' => 'hulk_1.webp', 'link_compra' => '../compra/hulk_1.php'],
  74 => ['categoria_id' => 2, 'nome' => 'A Saga Do Hulk 04', 'autor' => 'Jeph Loeb, Ian Churchill, John Romita Jr.', 'ano_publicacao' => 2025, 'paginas' => 144, 'isbn' => 'Não se aplica — revista periódica', 'editora' => 'Panini', 'descricao' => 'Com a família Hulk crescendo exponencialmente, era apenas uma questão de tempo até que as coisas chegassem a um ponto crítico. Mas o que poderia provocar a fúria de todos eles que os levasse a se voltar uns contra os outros… e contra o mundo? A morte de quem dá início a isso? Qual o papel de Skaar, as Mulheres-Hulk e o Universo Marvel nessa história? Uma coisa é certa: as coisas estão prestes a ficar incríveis!', 'preco' => 45.90, 'imagem' => 'hulk_2.webp', 'link_compra' => '../compra/hulk_2.php'],
  75 => ['categoria_id' => 2, 'nome' => 'A Saga Do Hulk 06', 'autor' => 'Jeph Loeb, Jeff Parker, Ed McGuinness, Gabriel Hardman', 'ano_publicacao' => 2025, 'paginas' => 216, 'isbn' => 'Não se aplica — revista periódica', 'editora' => 'Panini', 'descricao' => 'Quem viverá? Quem morrerá? O Universo Marvel conseguirá sobreviver com um Hulk verde e um Hulk vermelho? O Hulk Vermelho parte para lidar com um plano de contingência mortal deixado pelo Líder e por MODOC. Mas o Homem de Ferro não entendeu a mensagem. Para salvar o mundo, o Vermelhão precisa do Vingador mais poderoso, Thor, e entra em território profundamente desconhecido para impedir a próxima contingência, e o melhor aliado para a missão é Namor, rei da Atlântida! Rick Jones (também conhecido como Bomba-A) encontra a fonte do próximo cenário do Juízo Final e imediatamente se mete em encrenca no pedaço de terra mais perigoso do Pacífico... a Ilha dos Monstros! No fim, Bruce Banner encontra a chave para impedir o ataque da Intelligencia, e isso requer uma equipe de proporções épicas! Logo, os dois Hulks se unem para criar algo vermelho, verde e com infusão de gama!', 'preco' => 68.90, 'imagem' => 'hulk_3.webp', 'link_compra' => '../compra/hulk_3.php'],
  76 => ['categoria_id' => 2, 'nome' => 'O Incrível Hulk (2024) Vol. 02', 'autor' => 'Phillip Kennedy Johnson, Nic Klein', 'ano_publicacao' => 2024, 'paginas' => 136, 'isbn' => 'Não se aplica — revista periódica', 'editora' => 'Panini', 'descricao' => 'A JORNADA CONTINUA! Charlie relembra Bruce de que ele não é apenas um fugitivo, mas também um Vingador, um herói. E heróis ajudam as pessoas. Nesta edição, as viagens do gigante esmeralda e sua companheira adolescente vão leva-los ao Texas, onde seus caminhos serão cruzados com o de um Espírito da Vingança de 100 anos atrás! Para além disso, uma viagem ao tempo vai envolver o Hulk numa investigação noir centrada na busca por um assassino em série!', 'preco' => 34.90, 'imagem' => 'hulk_4.png', 'link_compra' => '../compra/hulk_4.php'],
  77 => ['categoria_id' => 2, 'nome' => 'Tales of Suspense (1959-1968) #39', 'autor' => 'Stan Lee, Larry Lieber, Don Heck, Jack Kirby', 'ano_publicacao' => 1963, 'paginas' => 13, 'isbn' => 'Não se aplica — fascículo avulso', 'editora' => 'Panini', 'descricao' => 'Observe sua incrível aproximação! Ouça seus passos pesados ​​enquanto ele se aproxima... cada vez mais... pois hoje você está destinado a encontrar - O INVENCÍVEL HOMEM DE FERRO!', 'preco' => 159, 'imagem' => 'iron_man_1.jpg', 'link_compra' => '../compra/iron_1.php'],
  78 => ['categoria_id' => 2, 'nome' => 'Invincible Iron Man Vol. 1: Reboot', 'autor' => 'Brian Michael Bendis, David Marquez', 'ano_publicacao' => 2016, 'paginas' => 136, 'isbn' => '9780785195207', 'editora' => 'Panini', 'descricao' => 'Um dos super-heróis mais populares do mundo alça voo para novas alturas! Tony Stark tem uma nova armadura, um novo elenco de apoio, novos vilões e um novo propósito que vai impactar todo o Universo Marvel e além. Tudo começa com uma reviravolta chocante e fica ainda mais surpreendente a partir daí, com o retorno de um dos maiores inimigos de Tony e a busca por seus pais biológicos! Enquanto o Homem de Ferro persegue Madame Máscara, suas ações ameaçam destruir toda a realidade! A incrível armadura do Cabeça de Lata será posta à prova em uma história que vai chocar e impressionar – mas é exatamente com quem Tony se alia que vai dar o que falar. Brian Michael Bendis pega o gênio, bilionário, playboy e filantropo e o transforma em uma superestrela!', 'preco' => 213.74, 'imagem' => 'iron_man_2.jpg', 'link_compra' => '../compra/iron_2.php'],
  79 => ['categoria_id' => 2, 'nome' => 'O Invencível Homem De Ferro Omnibus Vol. 4', 'autor' => 'Bill Mantlo, Bob Layton, John Romita Jr.', 'ano_publicacao' => 2025, 'paginas' => 856, 'isbn' => '9786525936949', 'editora' => 'Panini', 'descricao' => 'Neste Omnibus, Tony Stark enfrenta a épica Guerra dos Supervilões, entra em confronto com inimigos como Mandarim, M.O.D.O.K. e Garra Amarela, além de formar alianças com heróis como Demolidor e Homem-Coisa. A fase escrita por Bill Mantlo também apresenta uma armadura aprimorada, o retorno de Madame Máscara e novas ameaças que consolidam a evolução do Homem de Ferro nos anos 1970.', 'preco' => 645.92, 'imagem' => 'iron_man_3.webp', 'link_compra' => '../compra/iron_3.php'],
  80 => ['categoria_id' => 2, 'nome' => 'Invincible Iron Man by Gerry Duggan Vol. 1: Demon In The Armor', 'autor' => 'Gerry Duggan, Juan Frigeri', 'ano_publicacao' => 2023, 'paginas' => 152, 'isbn' => '9781302947583', 'editora' => 'Panini', 'descricao' => 'Tony Stark perdeu tudo. Sua empresa, seu dinheiro – talvez até sua sobriedade. Mas Stark não percebe que ainda tem muito mais a perder, especialmente quando assassinos começam a persegui-lo! Enquanto um inimigo conhecido retorna para destruí-lo de uma vez por todas, pelo menos Coração de Ferro está ao lado de Tony. Mas que segredo Riri Williams guarda, e isso mudará o relacionamento deles para sempre? Logo, outro amigo próximo é encontrado morto – e tudo indica que Tony é o assassino. Quem é o verdadeiro assassino? Por que estão tentando incriminar o Homem de Ferro? E até onde irão para atingir tudo o que ele ama? Tudo isso, além de Emma Frost! Uma nova armadura para o Máquina de Combate! E a história inédita de… Homem de Ferro contra os Vingadores da Costa Oeste?!', 'preco' => 101.17, 'imagem' => 'iron_man_4.jpg', 'link_compra' => '../compra/iron_4.php'],
  81 => ['categoria_id' => 2, 'nome' => 'Amazing Fantasy #15', 'autor' => 'Stan Lee, Steve Ditko', 'ano_publicacao' => 1962, 'paginas' => 36, 'isbn' => 'Não se aplica — fascículo avulso', 'editora' => 'Panini', 'descricao' => 'A edição histórica que revolucionou a indústria e apresentou o Incrível Homem-Aranha! Quando o tímido adolescente Peter Parker é picado por uma aranha radioativa, sua vida se transforma — primeiro para melhor, depois para pior! Com seu novo arsenal de habilidades aracnídeas — incluindo velocidade, força, agilidade e, graças ao seu conhecimento científico, a capacidade de tecer teias — Peter busca a fama como a celebridade mascarada conhecida como Homem-Aranha! Mas sua atitude despreocupada logo volta para assombrá-lo e destruir a vida de seus amados Tio Ben e Tia May! Peter Parker está prestes a aprender uma lição poderosa, uma que nunca foi ensinada melhor do que por Stan Lee e Steve Ditko: Com grandes poderes vêm grandes responsabilidades! É uma das maiores histórias em quadrinhos da Marvel de todos os tempos, representada com ousadia em sua forma original, com anúncios e tudo! Reimprimindo AMAZING FANTASY (1962) #15.', 'preco' => 99, 'imagem' => 'amazing_fantasy.jpg', 'link_compra' => '../compra/spiderfantasy.php'],
  82 => ['categoria_id' => 2, 'nome' => 'The Amazing Spider-Man #1', 'autor' => 'Stan Lee, Steve Ditko', 'ano_publicacao' => 1963, 'paginas' => 32, 'isbn' => 'Não se aplica — fascículo avulso', 'editora' => 'Panini', 'descricao' => 'Reúne "Spider-Man!" de *Amazing Fantasy* nº 15 (1962); *The Amazing Spider-Man* nº 1-4, 9, 10, 13, 14, 17-19 (1963-1964); "Goodbye to Linda Brown" de *Strange Tales* nº 97 (1962); e "How Stan Lee and Steve Ditko Create Spider-Man!" de *The Amazing Spider-Man Annual* nº 1 (1964). É impossível imaginar a cultura popular americana sem a Marvel Comics. Por décadas, a Marvel publicou narrativas visuais inovadoras que prendem a atenção em múltiplos níveis: como metáforas para a experiência da diferença e da alteridade; como reflexões sobre a natureza fluida da identidade; e como marcos de excelência na tradição artística dos quadrinhos americanos, para citar apenas alguns exemplos.', 'preco' => 99, 'imagem' => 'the_amazing_1.jpg', 'link_compra' => '../compra/spider1.php'],
  83 => ['categoria_id' => 2, 'nome' => 'The Amazing Spider-Man #2', 'autor' => 'Stan Lee, Steve Ditko', 'ano_publicacao' => 1963, 'paginas' => 32, 'isbn' => 'Não se aplica — fascículo avulso', 'editora' => 'Panini', 'descricao' => '"Duelo até a Morte com o Abutre"
Um novo criminoso vestido de abutre está aterrorizando a cidade de Nova York. J. Jonah Jameson quer fotos para um artigo na revista NOW. Peter decide que, se conseguir tirar fotos dos abutres, poderá vendê-las para J. Jonah Jameson para ajudar sua Tia May.

"A Ameaça Inexplicável do Terrível Consertador"
O professor de Peter o recomenda como assistente de ciências do Professor Cobwell. Enquanto faz um favor para o professor, seu sentido aranha detecta um estranho traço de radiação na loja e no rádio que ele acabou de pegar.', 'preco' => 99, 'imagem' => 'the_amazing_2.jpg', 'link_compra' => '../compra/spider2.php'],
  84 => ['categoria_id' => 2, 'nome' => 'Amazing Spider-Man Omnibus Vol. 3', 'autor' => 'Stan Lee, John Romita Sr.', 'ano_publicacao' => 2022, 'paginas' => 1000, 'isbn' => '9781302945664', 'editora' => 'Panini', 'descricao' => 'As aventuras do super-herói mais azarado dos quadrinhos, o Incrível Homem-Aranha, continuam! Criada por Stan Lee, John Romita Sr., Gerry Conway, Gil Kane e Ross Andru, a saga que se segue irá cativá-lo como nenhuma outra história em quadrinhos da Marvel jamais fez. O Duende Verde está de volta! Gwen Stacy está desaparecida! E tudo culmina em um confronto no topo da Ponte George Washington que mudará Peter Parker para sempre! É a história que consolidou o Duende Verde como a personificação do mal — e para que você não pense que esse é o único marco nestas páginas, este Omnibus também apresenta a estreia do Justiceiro, o casamento da Tia May e do Doutor Octopus, a descida de Harry Osborn à loucura e um novo papel para Mary Jane Watson!', 'preco' => 299, 'imagem' => 'the_amazing_3.jpg', 'link_compra' => '../compra/spider3.php'],
  85 => ['categoria_id' => 2, 'nome' => 'Thor: O Renascer dos Deuses: Marvel Essenciais', 'autor' => 'J. Michael Straczynski, Olivier Coipel', 'ano_publicacao' => 2024, 'paginas' => 344, 'isbn' => '9786525929019', 'editora' => 'Panini', 'descricao' => 'Resgatado do esquecimento pós-Ragnarok por seu alter ego mortal, o dr. Donald Blake, o deus nórdico do trovão retorna ao panteão dos grandes heróis Marvel Comics mais uma vez pelas mãos de JM Straczynski e Olivier Coipel. Juntos, Blake e Thor eles devem fazer jus ao legado do mítico reino de Asgard e despertar os heróis imortais da Cidade Dourada - mesmo que o mundo não os queira de volta... e que o preço para tal retorno seja extremamente alto!', 'preco' => 93.90, 'imagem' => 'thor_1.jpg', 'link_compra' => '../compra/thor_1.php'],
  86 => ['categoria_id' => 2, 'nome' => 'Thor Filho De Asgard Vol. 1', 'autor' => 'Akira Yoshida, Greg Tocchini', 'ano_publicacao' => 2024, 'paginas' => 144, 'isbn' => '9786525929477', 'editora' => 'Panini', 'descricao' => 'Preso nas garras de Hela, Thor precisa desafiar a própria Deusa da Morte para poupar a vida de Lady Sif. Depois de tudo o que ele passou, será que seu tão famoso martelo encantado Mjölnir será de alguma ajuda? Ou será que ele finalmente provou ser digno apenas para morrer como um fracasso no submundo?', 'preco' => 45.90, 'imagem' => 'thor_2.jpg', 'link_compra' => '../compra/thor_2.php'],
  87 => ['categoria_id' => 2, 'nome' => 'Thor: O Deus Do Trovão Renasce', 'autor' => 'Jason Aaron, Mike Del Mundo, Christian Ward', 'ano_publicacao' => 2024, 'paginas' => 312, 'isbn' => '9786525928128', 'editora' => 'Panini', 'descricao' => 'Thor Odinson reconquista seu manto e, com ele, um novo e insano mundo de problemas! Ele pode não ter o Mjolnir, mas tem centenas de novos martelos! E vai precisar de cada um deles para deter o irrefreável Fanático! Depois, os filhos de Odin lutam lado a lado novamente quando Thor se reúne com Balder, seu irmão há muito perdido, para enfrentar os exércitos de duendes de fogo da Rainha das Cinzas! A guerra assola a terra dos mortos - mas poderá a paz ser alcançada com um casamento realizado em Hel? Com Hela como noiva, qual dos irmãos será o felizardo noivo?! E ainda: Loki! Thori, o cão do Hel!  Valquírias! E, num futuro muito, muito distante, o Rei Thor encontra o Velho Fênix e encara o Doutor Destino no fim dos tempos!', 'preco' => 159.90, 'imagem' => 'thor_3.jpg', 'link_compra' => '../compra/thor_3.php'],
  88 => ['categoria_id' => 2, 'nome' => 'Thor: Vikings', 'autor' => 'Garth Ennis, Glenn Fabry', 'ano_publicacao' => 2024, 'paginas' => 128, 'isbn' => '9786525931982', 'editora' => 'Panini', 'descricao' => 'Vítimas de uma maldição conjurada da dor e do sofrimento, um bando de vikings é condenado a viver eternamente como corpos em decomposição navegando pelo mar por séculos até encontrar terra firme. A maldição chega ao fim quando eles chegam a atual Ilha de Manhattan e desembarcam trazendo morte e destruição aos habitantes do lugar. Caberá a Thor detê-los, mas derrotar uma horda vikings violentos, putrefatos e imbatíveis parece ser uma tarefa além das capacidades do Deus do Trovão. Publicada originalmente como parte da linha Marvel Max, a minissérie Thor: Vikings é escrita pelo polêmico Garth Ennis e ilustrada pelo elogiado artista Glenn Fabry.', 'preco' => 64.90, 'imagem' => 'thor_4.jpg', 'link_compra' => '../compra/thor_4.php'],
  89 => ['categoria_id' => 2, 'nome' => 'Os Vingadores Vol. 55', 'autor' => 'Jason Aaron, Javier Garrón', 'ano_publicacao' => 2024, 'paginas' => 136, 'isbn' => 'Não se aplica — revista periódica', 'editora' => 'Panini', 'descricao' => 'O Comando de Steve Rogers. A força aérea interestelar das Carol Corps. Pantera Estelar. O Deus dos Punhos. O Invencível Homem-Formiga, Tony Stark. As netas de Thor e um Wolverine que nunca existiu. Juntos, eles são o maior exército de Vingadores que já foi reunido. Mas serão o suficiente para proteger a grandiosa Torre dos Vingadores? Porque Mefisto se aproxima com sua armada procurando os segredos da Torre, e a batalha que está por vir será diferente de tudo que os heróis já viram antes - e nesse confronto entre Vingadores e Mestres do Terror Multiversal, nem todos sobreviverão. Em seguida, Thor enfrentará o Doutor Destino numa batalha de determinação, força e coragem - e o que está em jogo, além de Asgard, é a realidade em si!', 'preco' => 31.90, 'imagem' => 'vingadores_1.png', 'link_compra' => '../compra/vingadores_1.php'],
  90 => ['categoria_id' => 2, 'nome' => 'Os Vingadores 20/77', 'autor' => 'Jed MacKay, Farid Karami, Spencer Ackerman', 'ano_publicacao' => 2026, 'paginas' => 48, 'isbn' => 'Não se aplica — revista periódica', 'editora' => 'Panini', 'descricao' => 'Uma nova e brutal era começa para o Homem de Ferro! Tony Stark parte para a guerra com uma nova armadura para enfrentar velhos inimigos  e enfrentar inacreditáveis reviravoltas em histórias escritas pelo jornalista vencedor do Prêmio Pulitzer, Spencer Ackerman! E, nos Vingadores, o Pantera Negra assume o protagonismo em uma missão numa dimensão compacta enquanto os Vingadores enfrentam o Doutor Destino!', 'preco' => 15.95, 'imagem' => 'vingadores_2.webp', 'link_compra' => '../compra/vingadores_2.php'],
  91 => ['categoria_id' => 2, 'nome' => 'Vingadores: Beyonder', 'autor' => 'Jed MacKay, C.F. Villa', 'ano_publicacao' => 2025, 'paginas' => 112, 'isbn' => 'Não se aplica — revista periódica', 'editora' => 'Panini', 'descricao' => 'Alguém tem manipulado os Vingadores por meses, alterando o tecido da realidade numa tentativa de preparar o planeta para uma ameaça que pode vir a destruir tudo. Agora, esse mestre das marionetes está prestes a ser revelado de uma vez por todas. Enquanto isso, numa Nova York devastada pela violência, Janet Van Dyne luta não apenas para salvar as vidas de seus companheiros heroicos, mas também uma amizade! Mas o tempo pode estar acabando, pois o Perdido chegou e está esperando que a porta seja aberta para sua desastrosa entrada no planeta!', 'preco' => 31.90, 'imagem' => 'vingadores_3.png', 'link_compra' => '../compra/vingadores_3.php'],
  92 => ['categoria_id' => 2, 'nome' => 'Os Vingadores Vol. 54', 'autor' => 'Jason Aaron, Javier Garrón', 'ano_publicacao' => 2024, 'paginas' => 136, 'isbn' => 'Não se aplica — revista periódica', 'editora' => 'Panini', 'descricao' => 'Vingadores, Vingadores para Sempre, Vingadores de 1.000.000 A.E.C. - todos unidos numa saga épica em que, através do tempo e dos confins mais distantes do Multiverso, os Mais Poderosos Heróis de Todas as Terras juntam forças para uma batalha que vai além de tudo que qualquer um é capaz de imaginar. Um mal sem precedentes veio se fortalecendo e agora se ergue, ameaçando a Terra pelas mãos dos maiores vilões que já existiram. Será esse o fim dos Mestres do Terror do Multiverso - ou o fim de toda a história da Marvel como a conhecemos? Em seguida, em meio à jornada pelo resgate da pequena irmã de Thor, o Deus do Trovão e a guerreira Rúna se encontram face a face com o Rei Bor em pele e osso! E... Thanos? Que segredos obscuros e sangrentos da história de Asgard serão revelados, e quais serão seus impactos no futuro do Universo Marvel?', 'preco' => 31.90, 'imagem' => 'vingadores_4.png', 'link_compra' => '../compra/vingadores_4.php'],
  93 => ['categoria_id' => 2, 'nome' => 'SPIDER-MAN 1', 'autor' => 'Dan Slott e equipe criativa Marvel', 'ano_publicacao' => 2008, 'paginas' => 120, 'isbn' => '9780785128991', 'editora' => 'Panini', 'descricao' => 'Marca a primeira aparição do Homem-Aranha nos quadrinhos, em 1962. A história mostra Peter Parker, um
        adolescente tímido que ganha poderes após ser picado por uma aranha radioativa. No início, ele usa seus poderes
        para fama e dinheiro, mas após a morte de seu tio Ben, aprende a importante lição: “Com grandes poderes vêm
        grandes responsabilidades.”', 'preco' => 34.90, 'imagem' => 'spider-man-1.png', 'link_compra' => '../compra/CompraSpider.php'],
  94 => ['categoria_id' => 3, 'nome' => 'Aquaman Vol. 01', 'autor' => 'Jeremy Adams, John Timms', 'ano_publicacao' => 2025, 'paginas' => 144, 'isbn' => 'Não se aplica — revista periódica', 'editora' => 'Panini', 'descricao' => 'Aquaman entra da era Sem Limites! Após os eventos de Poder Absoluto, os poderes de Arthur Curry evoluíram fantasticamente. Construtos colossais emergiram de cada um dos sete mares, e somente as habilidades de manipulação aquática do Aquaman serão capazes de detê-los... exceto se a realeza for morta no processo. O lar do Rei dos Mares será ameaçado? Talvez ele precise treinar como nunca para ter qualquer chance de recuperar a Atlântida de seu apocalipse anunciado. Quais segredos mortais aguardam Arthur nessa jornada?', 'preco' => 59.90, 'imagem' => 'aquaman_1.webp', 'link_compra' => '../compra/aquaman_1.php'],
  95 => ['categoria_id' => 3, 'nome' => 'Aquaman: A Busca Por Mera', 'autor' => 'Steve Skeates, Jim Aparo', 'ano_publicacao' => 2024, 'paginas' => 216, 'isbn' => '9786525924137', 'editora' => 'Panini', 'descricao' => 'Mera, a rainha da Atlântida, desaparece misteriosamente. Enquanto Aquaman inicia sua busca desesperada em todos os lugares, seu reino está nas garras de um novo inimigo chamado Narkran, um ardiloso político com planos para usurpar o trono e governar com mão de ferro! Por fim, como se a situação não fosse ruim o suficiente, o Arraia Negra aparece para tirar vantagem do apuro do Aquaman! Um clássico escrito por Steve Skeates e desenhado pelo lendário Jim Aparo!', 'preco' => 52.45, 'imagem' => 'aquaman_2.jpg', 'link_compra' => '../compra/aquaman_2.php'],
  96 => ['categoria_id' => 3, 'nome' => 'Aquaman Por Peter David Vol. 1', 'autor' => 'Peter David, Kirk Jarvinen, Martin Egeland', 'ano_publicacao' => 2025, 'paginas' => 320, 'isbn' => '9786525933511', 'editora' => 'Panini', 'descricao' => 'A clássica fase de Peter David em Aquaman começa neste volume! Desde seu abandono em um recife até sua criação por um golfinho e seu primeiro encontro com os habitantes da superfície, essas histórias narram a origem e a ascensão da figura mítica conhecida como Aquaman.', 'preco' => 164.90, 'imagem' => 'aquaman_3.jpg', 'link_compra' => '../compra/aquaman_3.php'],
  97 => ['categoria_id' => 3, 'nome' => 'Aquaman Por Peter David Vol. 2', 'autor' => 'Peter David, Jim Calafiore, Martin Egeland', 'ano_publicacao' => 2026, 'paginas' => 344, 'isbn' => '9786525936291', 'editora' => 'Panini', 'descricao' => 'Assim como o capitão é o último a abandonar o navio que está afundando, Aquaman é o último a abandonar Atlântida quando ela está… emergindo! No momento em que a mais importante cidade do reino aquático sofre estranhos tremores, seu povo não hesita em abandoná-la com medo de uma catástrofe maior, e cabe ao herói descobrir por que a metrópole está ascendendo para além do nível do mar. 
                
                Ao mergulharem fundo nos segredos da antiga cidade submarina, Aquaman e sua nova parceira, Delfim, encontrarão perigos que remontam não apenas ao passado de Atlântida, mas também do próprio herói. E como um rei nunca tem sossego, a situação fica ainda mais complicada com o retorno da rainha Mera, que terá muito a dizer sobre a proximidade do ex-esposo com Delfim.', 'preco' => 172.90, 'imagem' => 'aquaman_4.jpg', 'link_compra' => '../compra/aquaman_4.php'],
  98 => ['categoria_id' => 3, 'nome' => 'Batman: Cataclismo', 'autor' => 'Alan Grant, Chuck Dixon, Doug Moench, Jim Aparo, Mark Buckingham, Scott McDaniel', 'ano_publicacao' => 2026, 'paginas' => 480, 'isbn' => '9786525941257', 'editora' => 'Panini', 'descricao' => 'Existe um inimigo que o Batman pode ver e ouvir, porém não pode tocar. Só haverá um ataque, mas isso vai mudar a vida do Cavaleiro das Trevas para sempre. Já enfraquecida por uma praga debilitante, Gotham City é atingida por uma inesperada força da natureza, um terremoto que registra mais de 7,5 na escala Richter. Num único instante, a Batcaverna e a Mansão Wayne ficam em ruínas, milhares morrem e o Batman está entre os desaparecidos.', 'preco' => 133.52, 'imagem' => 'batman_1.png', 'link_compra' => '../compra/batman_1.php'],
  99 => ['categoria_id' => 3, 'nome' => 'Batman/Spawn', 'autor' => 'Todd McFarlane, Greg Capullo', 'ano_publicacao' => 2023, 'paginas' => 112, 'isbn' => '9786559829781', 'editora' => 'Panini', 'descricao' => 'Dois heróis sombrios, marcados pela tragédia, encontram seus caminhos se cruzando novamente...
            mas não por escolha. Que inimigo sinistro está em ação colocando o Cavaleiro das Trevas contra
            o Spawn? Das sombras de Gotham City à cidade de Nova York, é a realização do encontro que os
            fãs aguardavam há quase duas décadas.', 'preco' => 23.12, 'imagem' => 'batman_2.jpg', 'link_compra' => '../compra/batman_2.php'],
  100 => ['categoria_id' => 3, 'nome' => 'Batman: Fortaleza', 'autor' => 'Gary Whitta, Darick Robertson', 'ano_publicacao' => 2023, 'paginas' => 208, 'isbn' => '9786559827992', 'editora' => 'Panini', 'descricao' => 'Quando uma nave alienígena desconhecida entra na atmosfera da Terra, interrompendo o poder e as comunicações globais e mergulhando o planeta no caos, o mundo fica se perguntando… onde está o Superman quando ele é mais necessário? Na misteriosa ausência do Último Filho de Krypton, Batman deve reunir o resto da Liga da Justiça para combater a ameaça alienígena… mas, primeiro, ele deve reprimir uma violenta onda de crimes nas ruas de Gotham! Uma aventura chocante que vai virar de cabeça para baixo tudo o que você acha que sabe sobre o Superman!', 'preco' => 71.92, 'imagem' => 'batman_3.png', 'link_compra' => '../compra/batman_3.php'],
  101 => ['categoria_id' => 3, 'nome' => 'Batman 31/113', 'autor' => 'Chip Zdarsky, Jorge Jiménez', 'ano_publicacao' => 2025, 'paginas' => 48, 'isbn' => 'Não se aplica — revista periódica', 'editora' => 'Panini', 'descricao' => 'Batman retornou, mas sua cidade não é a mesma que ele conheceu. uma ordem sinistra agora governa as sombras de Gotham. Uma ordem tão precisa, tão metódica, que apenas uma coisa conseguiria combatê-la… O que será esta força singular?', 'preco' => 25.52, 'imagem' => 'batman_4.jpg', 'link_compra' => '../compra/batman_4.php'],
  102 => ['categoria_id' => 3, 'nome' => 'O Asilo Do Coringa', 'autor' => 'Alex Sanchez, Andy Clarke, Arvid Nelson, David Hine, Guillem March, J.T. Krul, Jason Aaron, Jason Pearson, Joe Harris, Juan Doe', 'ano_publicacao' => 2024, 'paginas' => 248, 'isbn' => '9786525930848', 'editora' => 'Panini', 'descricao' => 'Participe de uma jornada psicótica narrada pelo maior e mais perturbado inimigo do Batman, o Coringa, para explorar a psicose de vários dos mais célebres vilões do Cavaleiro das Trevas em dez contos próprios: o Pinguim, a Hera Venenosa, o Espantalho, o Duas-Caras, o Charada, a Arlequina, o Chapeleiro Louco, o Crocodilo e o Cara de Barro! Além, claro, do próprio Príncipe Palhaço do Crime!', 'preco' => 114.90, 'imagem' => 'coringa_1.webp', 'link_compra' => '../compra/coringa_1.php'],
  103 => ['categoria_id' => 3, 'nome' => 'Coringa: O Mundo', 'autor' => 'Felipe Castilho, Geoff Johns, Jason Fabok, Mariane Gusmão, Satoshi Miyagawa, Tainan Rocha', 'ano_publicacao' => 2024, 'paginas' => 168, 'isbn' => '9786525933580', 'editora' => 'Panini', 'descricao' => 'Em uma iniciativa global que começou com a antologia Batman: O Mundo, autores de todo o planeta apresentam sua visão única do Príncipe Palhaço do Crime… que está prestes a dominar muito mais do que apenas Gotham City. Existe todo um mundo para aterrorizar, e o vilão viajará ao redor do globo, dos Estados Unidos até o Brasil, passando por Argentina, diversos países da Europa e muitos outros locais, fazendo o que sabe de melhor: criando o caos!', 'preco' => 89.90, 'imagem' => 'coringa_2.jpg', 'link_compra' => '../compra/coringa_2.php'],
  104 => ['categoria_id' => 3, 'nome' => 'Coringa: A Era De Bronze Omnibus', 'autor' => 'Bob Haney, Dennis O\'Neil, Dick Dillin, Elliot Maggin, Jim Aparo, José Luis García-López, Marshall Rogers, Martin Pasko, Neal Adams, Steve Englehart', 'ano_publicacao' => 2024, 'paginas' => 832, 'isbn' => '9786525930992', 'editora' => 'Panini', 'descricao' => 'A rivalidade entre o Príncipe Palhaço do Crime e o Homem-Morcego existe há muitos anos! Com a passagem da década de 1960 para os anos 1970, o Coringa também sofreu algumas alterações e tornou-se ligeiramente diferente do que os leitores conheciam até então. Acompanhe a mudança na personalidade do vilão, se afastando do viés cômico instaurado pela representação do ator Cesar Romero e tornando-se um maníaco diabólico que marcaria a era moderna do Batman, em uma seleção de histórias escritas e desenhadas pelos maiores nomes da DC!', 'preco' => 339.90, 'imagem' => 'coringa_3.webp', 'link_compra' => '../compra/coringa_3.php'],
  105 => ['categoria_id' => 3, 'nome' => 'Coringa: O Homem Que Parou De Rir Vol. 1', 'autor' => 'Matthew Rosenberg, Carmine Di Giandomenico, Francesco Francavilla', 'ano_publicacao' => 2023, 'paginas' => 224, 'isbn' => '9786559829316', 'editora' => 'Panini', 'descricao' => 'O mundo mais uma vez prende a respiração enquanto o Coringa ataca novamente! Mas até onde ele está disposto a ir desta vez? Das mentes insanas de Matthew Rosenberg (DC vs. Vampiros) e Carmine Di Giandomenico (Batman: O Cavaleiro), surge uma nova série violenta e alucinante que começa a partir do final cataclísmico da minissérie O Coringa e segue para um completo caos nos Estados Unidos.', 'preco' => 69.90, 'imagem' => 'coringa_4.jpg', 'link_compra' => '../compra/coringa_4.php'],
  106 => ['categoria_id' => 3, 'nome' => 'Flash: Ano Um', 'autor' => 'Joshua Williamson, Howard Porter', 'ano_publicacao' => 2020, 'paginas' => 152, 'isbn' => '9786555120776', 'editora' => 'Panini', 'descricao' => 'Barry Allen inicia sua jornada como o homem mais rápido do mundo após um acidente em seu laboratório.
            Nesta história, acompanhamos os primeiros desafios do Flash, sua adaptação aos novos poderes e o início
            de sua carreira como um dos maiores heróis da Liga da Justiça.', 'preco' => 49.90, 'imagem' => 'flash1.jpg', 'link_compra' => '../compra/flash1.php'],
  107 => ['categoria_id' => 3, 'nome' => 'Flash: Renascimento', 'autor' => 'Geoff Johns, Ethan Van Sciver', 'ano_publicacao' => 2011, 'paginas' => 176, 'isbn' => '9788573518597', 'editora' => 'Panini', 'descricao' => 'Barry Allen está de volta.

            Após anos afastado, o maior velocista da DC Comics retorna em uma das histórias mais importantes do personagem.

            Nesta edição, Barry precisa descobrir quem está por trás de uma série de acontecimentos envolvendo a Força de Aceleração enquanto enfrenta antigos inimigos e reencontra aliados da Liga da Justiça.

            Uma história emocionante, repleta de ação, mistério e momentos marcantes para todos os fãs do Flash.', 'preco' => 49.90, 'imagem' => 'flash2.jpg', 'link_compra' => '../compra/flash2.php'],
  108 => ['categoria_id' => 3, 'nome' => 'Flash: Ponto de Ignição', 'autor' => 'Geoff Johns, Andy Kubert', 'ano_publicacao' => 2012, 'paginas' => 168, 'isbn' => '9788583680444', 'editora' => 'Panini', 'descricao' => 'Barry Allen acorda em uma realidade completamente diferente após tentar salvar sua mãe.

            Sem seus poderes e diante de um mundo prestes a entrar em guerra, o Flash precisa recuperar sua velocidade para restaurar a linha do tempo antes que seja tarde demais.

            Enquanto isso, Batman é Thomas Wayne, Superman nunca se tornou um herói e o conflito entre Aquaman e Mulher-Maravilha ameaça destruir o planeta.

            Uma das histórias mais importantes da DC Comics, responsável por dar origem ao universo dos Novos 52.', 'preco' => 89.90, 'imagem' => 'flash3.jpg', 'link_compra' => '../compra/flash3.php'],
  109 => ['categoria_id' => 3, 'nome' => 'Flash: A Guerra dos Flashes', 'autor' => 'Joshua Williamson, Howard Porter', 'ano_publicacao' => 2019, 'paginas' => 160, 'isbn' => '9788542625769', 'editora' => 'Panini', 'descricao' => 'Barry Allen enfrenta sua maior batalha quando o misterioso Professor Zoom retorna para destruir tudo o que o Flash mais ama.

            Em meio a perseguições eletrizantes e viagens através da Força de Aceleração, Barry precisa enfrentar seu maior inimigo enquanto tenta proteger seus amigos, sua família e toda Central City.

            Repleta de ação, reviravoltas e momentos marcantes, Flash: A Guerra dos Flashes é uma das histórias mais emocionantes do Velocista Escarlate.', 'preco' => 59.90, 'imagem' => 'flash4.jpg', 'link_compra' => '../compra/flash4.php'],
  110 => ['categoria_id' => 3, 'nome' => 'Lanterna Verde (2024) 04', 'autor' => 'Jeremy Adams, Xermánico', 'ano_publicacao' => 2024, 'paginas' => 48, 'isbn' => 'Não se aplica — revista periódica', 'editora' => 'Panini', 'descricao' => 'O tempo de John Stewart servir como Lanterna Verde chegou ao fim… ou assim ele pensava. Uma tragédia familiar o chama de volta para casa, e, à medida que John começa a recuperar a carreira que deixou para trás, ele tenta abraçar uma vida pacífica. Mas, quando uma força terrível e contagiosa com uma misteriosa conexão com Oa surge na Terra, o último Lanterna Verde de outro universo vem em busca do único guerreiro que pode enfrentar esta ameaça e vencer: o próprio John Stewart!', 'preco' => 24.90, 'imagem' => 'lanterna_1.webp', 'link_compra' => '../compra/lanterna_1.php'],
  111 => ['categoria_id' => 3, 'nome' => 'Lanterna Verde (2024) 09', 'autor' => 'Jeremy Adams, Xermánico', 'ano_publicacao' => 2024, 'paginas' => 48, 'isbn' => 'Não se aplica — revista periódica', 'editora' => 'Panini', 'descricao' => 'Hal Jordan está preso na Terra! Incapaz de deixar a atmosfera, o Lanterna Verde procura ajuda de uma fonte mística, que o leva a um portal misterioso e a desvendar respostas surpreendentes sobre a origem do anel de Hal. E ainda: a climática conclusão do primeiro arco de Lanterna Verde: Diário de Guerra! Para salvar a Terra, John Stewart terá que desbloquear o seu potencial como o lendário "Guardião e Construtor"! Descubra as origens secretas da Tropa dos Lanternas Verdes e dos Darkstars!', 'preco' => 19.90, 'imagem' => 'lanterna_2.webp', 'link_compra' => '../compra/lanterna_2.php'],
  112 => ['categoria_id' => 3, 'nome' => 'Absolute Lanterna Verde 01', 'autor' => 'Al Ewing, Jahnoy Lindsay', 'ano_publicacao' => 2025, 'paginas' => 32, 'isbn' => 'Não se aplica — revista periódica', 'editora' => 'Panini', 'descricao' => 'Sem a Tropa, sem o anel e sem a força de vontade. O que resta é o Lanterna Verde absoluto! Abin Sur chegou e está aqui para julgar todas as pessoas de Evergreen, incluindo Jo Mullein e Hal Jordan. Mas esse ser alienígena é amigo ou inimigo? E o que exatamente seu julgamento trará?', 'preco' => 19.90, 'imagem' => 'lanterna_3.webp', 'link_compra' => '../compra/lanterna_3.php'],
  113 => ['categoria_id' => 3, 'nome' => 'Lanterna Verde (2025) 02', 'autor' => 'Jeremy Adams, Xermánico', 'ano_publicacao' => 2025, 'paginas' => 48, 'isbn' => 'Não se aplica — revista periódica', 'editora' => 'Panini', 'descricao' => 'As sementes da guerra foram plantadas, e agora uma grande batalha se desenrola pela galáxia! Hal Jordan, John Stewart e Guy Gardner precisam correr para desvendar o mistério da ressurreição da Estrela Negra, o que isso significa para seu querido amigo Kilowog e como lutar contra um planeta inteiro!', 'preco' => 19.90, 'imagem' => 'lanterna_4.webp', 'link_compra' => '../compra/lanterna_4.php'],
  114 => ['categoria_id' => 3, 'nome' => 'Liga Da Justiça Vs Godzilla Vs Kong', 'autor' => 'Brian Buccellato, Christian Duce, Tom Derenick', 'ano_publicacao' => 2025, 'paginas' => 264, 'isbn' => '9786525925820', 'editora' => 'Panini', 'descricao' => 'Como destruir a Liga da Justiça? Essa é a pergunta que atormenta Lex Luthor e sua Legião do Mal desde os primeiros confrontos entre os dois grupos titânicos. Agora, ao se deparar com as colossais entidades da Ilha da Caveira, Lex acredita ter encontrado a resposta para essa questão eterna. É Superman contra Godzilla, Mulher-Maravilha contra Behemoth, Lanterna Verde contra Scylla, Batman contra Camazotz e Supergirl contra Kong, em uma batalha épica pelo destino do Universo DC.', 'preco' => 45.95, 'imagem' => 'liga_1.webp', 'link_compra' => '../compra/ligadajustica_1.php'],
  115 => ['categoria_id' => 3, 'nome' => 'Liga Da Justiça Da América: Ano Um', 'autor' => 'Barry Kitson, Brian Augustyn, Mark Waid', 'ano_publicacao' => 2024, 'paginas' => 328, 'isbn' => '9786525923017', 'editora' => 'Panini', 'descricao' => 'A origem da Liga da Justiça da América pelas mãos do aclamado roteirista Mark Waid! Saiba como os cinco membros fundadores da LJA (Flash, Lanterna Verde, Canário Negro, Caçador de Marte e Aquaman) conseguiram se unir como uma equipe, ganhando o respeito do público e derrotando inimigos como Vandal Savage, os appellaxianos, o cientista F.U. Turo e a Irmandade Negra, e testemunhe os primeiros encontros com outros heróis como o Superman e a Patrulha do Destino!', 'preco' => 74.95, 'imagem' => 'liga_2.webp', 'link_compra' => '../compra/ligadajustica_2.php'],
  116 => ['categoria_id' => 3, 'nome' => 'Liga Da Justiça Sem Limites (2025) 12', 'autor' => 'Mark Waid, Saladin Ahmed', 'ano_publicacao' => 2026, 'paginas' => 48, 'isbn' => 'Não se aplica — revista periódica', 'editora' => 'Panini', 'descricao' => 'O Rei Ômega chegou e o universo está ameaçado! A Terra se tornou um lugar hostil, violento… e condenado. Cabe à equipe dos seres mais poderosos (e temporalmente deslocados), organizada pelo Senhor Incrível, encontrar o coração das trevas no núcleo do planeta. Ao mesmo tempo, a Liga da Justiça Vermelha se organiza para ir até Adão Negro, onde reside um dos mistérios do futuro do planeta.', 'preco' => 19.90, 'imagem' => 'liga_3.webp', 'link_compra' => '../compra/ligadajustica_3.php'],
  117 => ['categoria_id' => 3, 'nome' => 'A Saga Da Liga Da Justiça 03/19', 'autor' => 'Brad Meltzer, Dale Eaglesham, Ed Benes, Gene Ha, Geoff Johns', 'ano_publicacao' => 2024, 'paginas' => 144, 'isbn' => '9786525916545', 'editora' => 'Panini', 'descricao' => 'No volume que encerra a fase de Brad Meltzer no comando dos roteiros da revista da LJA, o crossover entre a Liga da Justiça e a Sociedade da Justiça chega ao fim com os heróis investigando de Gorilla City a Thanagar, e um personagem faz seu retorno triunfal ao Universo DC! Além disso, dois membros da LJA são enterrados vivos em uma história à parte, vencedora do Prêmio Eisner!', 'preco' => 19.95, 'imagem' => 'liga_4.webp', 'link_compra' => '../compra/ligadajustica_4.php'],
  118 => ['categoria_id' => 3, 'nome' => 'Mulher-Maravilha: Hiketeia', 'autor' => 'Greg Rucka, J.G. Jones', 'ano_publicacao' => 2025, 'paginas' => 128, 'isbn' => '9786559825387', 'editora' => 'Panini', 'descricao' => 'O conto mais aguardado de todos os tempos que reúne Mulher-Maravilha e Batman está de volta, em uma nova e mais completa edição de luxo! Um ritual antigo e há muito esquecido liga Diana a uma jovem de Gotham City, que tem um passado extremamente conturbado… Pior ainda, a Mulher-Maravilha é forçada ao assumir o papel de sua professora e protetora, mas logo descobre que ela também deve ficar entre sua aluna e a justiça terrena que o Cavaleiro das Trevas tão certeiramente busca! O que acontecerá quando a Princesa de Themyscira tiver que defender sua protegida da justiça do Cruzado Encapuzado?', 'preco' => 37.95, 'imagem' => 'mulhermara_1.jpg', 'link_compra' => '../compra/mulhermara_1.php'],
  119 => ['categoria_id' => 3, 'nome' => 'Mulher-Maravilha: Evolução', 'autor' => 'Stephanie Phillips, Mike Hawthorne', 'ano_publicacao' => 2023, 'paginas' => 192, 'isbn' => '9786559828869', 'editora' => 'Panini', 'descricao' => 'Arrastada da Terra por uma entidade cósmica distante, a Mulher-Maravilha é forçada a enfrentar uma série de desafios perigosos que a levam ao limite, tanto mental quanto fisicamente. Em jogo está o destino de toda a humanidade, com as entidades alienígenas lançando Diana como representante da Terra para um julgamento que definirá o valor da humanidade para existir no universo.', 'preco' => 47.92, 'imagem' => 'mulhermara_2.jpg', 'link_compra' => '../compra/mulhermara_2.php'],
  120 => ['categoria_id' => 3, 'nome' => 'Mulher-Maravilha/Flash 15', 'autor' => 'Tom King, Daniel Sampere e equipe DC', 'ano_publicacao' => 2025, 'paginas' => 48, 'isbn' => 'Não se aplica — revista periódica', 'editora' => 'Panini', 'descricao' => 'A Mulher-Maravilha faz parte de uma nova dupla com o mais improvável de seus aliados: Robin! Em uma missão ultrassecreta para salvar seus heróis companheiros, a busca de Damian e Diana para invadir a prisão de Waller será bem-sucedida? Ou é uma armadilha elaborada pela Muralha para capturar a Mulher-Maravilha e o seu ajudante? E mais: Flash e Grodd se encontram em uma improvável história de amor com suas companheiras.', 'preco' => 18.32, 'imagem' => 'mulhermara_3.jpg', 'link_compra' => '../compra/mulhermara_3.php'],
  121 => ['categoria_id' => 3, 'nome' => 'Absolute Mulher-Maravilha 04', 'autor' => 'Kelly Thompson, Hayden Sherman', 'ano_publicacao' => 2025, 'paginas' => 32, 'isbn' => 'Não se aplica — revista periódica', 'editora' => 'Panini', 'descricao' => 'Depois que os mistérios do passado de Diana são revelados, a Mulher-Maravilha precisa enfrentar um novo desafio que faz o Tetracida parecer brincadeira de criança. No começo desta nova história, Diana precisa enfrentar um labirinto que esconde desafios inimagináveis…', 'preco' => 19.92, 'imagem' => 'mulhermara_4.jpg', 'link_compra' => '../compra/mulhermara_4.php'],
  122 => ['categoria_id' => 3, 'nome' => 'Superman: Ano Um', 'autor' => 'Frank Miller, John Romita Jr.', 'ano_publicacao' => 2020, 'paginas' => 216, 'isbn' => '9786555121131', 'editora' => 'Panini', 'descricao' => 'Do mundo ardente de Krypton aos campos bucólicos do Kansas, Superman: Ano Um acompanha a juventude de Clark Kent no Kansas, enquanto ele aceita seus estranhos poderes e luta para encontrar seu lugar em nosso mundo. Acompanhe o jovem Clark em uma viagem para a Atlântida! Lá ele conhece um novo povo, encontra o amor, enfrenta feras gigantescas e descobre o homem que deveria ser. O selo BLACK LABEL tem o orgulho de apresentar a origem definitiva do Superman, conforme apresentada por duas grandes lendas dos quadrinhos: Frank Miller e John Romita Jr.!', 'preco' => 59.90, 'imagem' => 'superman_1.jpg', 'link_compra' => '../compra/superman_1.php'],
  123 => ['categoria_id' => 3, 'nome' => 'Superman: As Quatro Estações (DC De Bolso)', 'autor' => 'Jeph Loeb, Tim Sale', 'ano_publicacao' => 2024, 'paginas' => 224, 'isbn' => '9786525924915', 'editora' => 'Panini', 'descricao' => 'Nesta história de amadurecimento, acompanhe as experiências e aventuras que transformam um simples garoto do interior no maior herói do mundo. Narrada ao longo das quatro estações do ano no início da carreira heroica do Superman, a obra mostra que é a pessoa, e não os poderes, que faz dele um verdadeiro herói. Uma jornada intensa e emocional, explorando cada aspecto humano que compõe a força, o caráter e a determinação do Homem de Aço.', 'preco' => 45.52, 'imagem' => 'superman_2.jpg', 'link_compra' => '../compra/superman_2.php'],
  124 => ['categoria_id' => 3, 'nome' => 'Superman: Grandes Astros', 'autor' => 'Grant Morrison, Frank Quitely', 'ano_publicacao' => 2023, 'paginas' => 304, 'isbn' => '9786559826643', 'editora' => 'Panini', 'descricao' => 'Setenta anos após ser criado e apresentado ao planeta por Joe Shuster e Jerry Siegel, Superman ganhou, no início dos anos 2000, uma reinterpretação surpreendente que chocou completa e positivamente o mundo das HQs e redefiniu todos os limites de um personagem icônico, que acreditava-se ser inalterável. Por cortesia da genial e excêntrica mente do roteirista Grant Morrison e do traço incomparável do desenhista Frank Quitely, o Homem de Aço (e seus milhões de fãs pelo mundo) foram presenteados com uma obra-prima sem precedentes, publicada em doze partes sob o título Grandes Astros Superman. Publicada no Brasil pela Panini em uma edição única e com o tratamento condizente à sua relevância e qualidade, a Edição Definitiva de Grandes Astros: Superman traz a história na íntegra em acabamento e formato diferenciados, e acompanhada por extras inéditos no Brasil! Testemunhe os maiores desafios do Homem de Aço até então, enfrentando ameaças alienígenas, adversários superpoderosos, os planos diabólicos de Lex Luthor e um destino final inexorável. Uma sincera e efusiva homenagem a tudo o que o personagem já viveu nas páginas das publicações em que estrela desde que foi criado por Jerry Siegel e Joe Shuster.', 'preco' => 68.80, 'imagem' => 'superman_3.jpg', 'link_compra' => '../compra/superman_3.php'],
  125 => ['categoria_id' => 3, 'nome' => 'A Morte do Superman', 'autor' => 'Dan Jurgens, Louise Simonson, Roger Stern, Jerry Ordway e equipe DC', 'ano_publicacao' => 2023, 'paginas' => 176, 'isbn' => '9786559827060', 'editora' => 'Panini', 'descricao' => 'Há 30 anos, o impossível aconteceu: o Homem de Aço morreu. O maior dos super-heróis se sacrificou para deter a ameaça global conhecida como Apocalypse. Para marcar o aniversário desse marco monumental dos quadrinhos, a editora do Superman reuniu a equipe de criação do evento original para produzir quatro histórias inéditas. Esta edição especial apresenta o Superman medindo forças com um novo vilão… o Hecatombe! E mais: três enredos curtos estrelados pelos maiores aliados do kryptoniano, e pinups exclusivos desenhados por talentos como Lee Weeks, Bill Sienkiewicz e Walter Simonson!', 'preco' => 27.92, 'imagem' => 'superman_4.jpg', 'link_compra' => '../compra/superman_4.php'],
];
