<?php
// Informações preservadas das páginas individuais e condições de exibição.
// id_banco registra os vínculos conferidos no banco enviado, sem renumerar registros.
return [
    93 => [
    'id_banco' => 93,
    'nome_original' => 'SPIDER-MAN 1',
    'imagem_original' => 'spider-man-1.png',
    'parcelas' => 2,
],
    94 => [
    'id_banco' => 94,
    'nome_original' => 'Aquaman Vol. 01',
    'imagem_original' => 'aquaman_1.webp',
    'parcelas' => 1,
],
    95 => [
    'id_banco' => 95,
    'nome_original' => 'Aquaman: A Busca Por Mera',
    'imagem_original' => 'aquaman_2.jpg',
    'parcelas' => 1,
],
    96 => [
    'id_banco' => 96,
    'nome_original' => 'Aquaman Por Peter David Vol. 1',
    'imagem_original' => 'aquaman_3.jpg',
    'parcelas' => 4,
],
    97 => [
    'id_banco' => 97,
    'nome_original' => 'Aquaman Por Peter David Vol. 2',
    'imagem_original' => 'aquaman_4.jpg',
    'parcelas' => 4,
],
    5 => [
    'id_banco' => 5,
    'nome_original' => 'Attack on Titan 1',
    'imagem_original' => 'attack_on_titan_1.jpg',
    'parcelas' => 1,
],
    6 => [
    'id_banco' => 6,
    'nome_original' => 'Attack on Titan 2',
    'imagem_original' => 'attack_on_titan_2.jpg',
    'parcelas' => 2,
],
    7 => [
    'id_banco' => 7,
    'nome_original' => 'Attack on Titan 3',
    'imagem_original' => 'attack_on_titan_3.jpg',
    'parcelas' => 2,
],
    4 => [
    'id_banco' => 4,
    'nome_original' => 'Attack on Titan 31',
    'imagem_original' => 'attack_on_titan_31.jpg',
    'parcelas' => 3,
],
    3 => [
    'id_banco' => 3,
    'nome_original' => 'Attack on Titan 32',
    'imagem_original' => 'attack_on_titan_32.jpg',
    'parcelas' => 2,
],
    2 => [
    'id_banco' => 2,
    'nome_original' => 'Attack on Titan 33',
    'imagem_original' => 'attack_on_titan_33.jpg',
    'parcelas' => 3,
],
    1 => [
    'id_banco' => 1,
    'nome_original' => 'Ataque dos titãs vol. 34',
    'imagem_original' => 'attack_on_titan_34.jpg',
    'parcelas' => 1,
],
    8 => [
    'id_banco' => 8,
    'nome_original' => 'Attack on Titan 4',
    'imagem_original' => 'attack_on_titan_4.jpg',
    'parcelas' => 2,
],
    98 => [
    'id_banco' => 98,
    'nome_original' => 'Batman: Cataclismo',
    'imagem_original' => 'batman_1.png',
    'parcelas' => 4,
],
    99 => [
    'id_banco' => 99,
    'nome_original' => 'Batman/Spawn',
    'imagem_original' => 'batman_2.jpg',
    'parcelas' => 1,
],
    100 => [
    'id_banco' => 100,
    'nome_original' => 'Batman: Fortaleza',
    'imagem_original' => 'batman_3.png',
    'parcelas' => 2,
],
    101 => [
    'id_banco' => 101,
    'nome_original' => 'Batman 31/113',
    'imagem_original' => 'batman_4.jpg',
    'parcelas' => 1,
],
    13 => [
    'id_banco' => 13,
    'nome_original' => 'Bleach, Vol. 1: Strawberry and the Soul Reapers',
    'imagem_original' => 'bleach_1.jpg',
    'parcelas' => 2,
],
    14 => [
    'id_banco' => 14,
    'nome_original' => 'Bleach vol. 2',
    'imagem_original' => 'bleach_2.jpg',
    'parcelas' => 1,
],
    15 => [
    'id_banco' => 15,
    'nome_original' => 'Bleach vol. 3',
    'imagem_original' => 'bleach_3.jpg',
    'parcelas' => 2,
],
    9 => [
    'id_banco' => 9,
    'nome_original' => 'Bleach, Vol. 33: The Bad Joke',
    'imagem_original' => 'bleach_33.jpg',
    'parcelas' => 1,
],
    10 => [
    'id_banco' => 10,
    'nome_original' => 'Bleach, Vol. 35: HIGHER THAN THE MOON',
    'imagem_original' => 'bleach_35.jpg',
    'parcelas' => 2,
],
    11 => [
    'id_banco' => 11,
    'nome_original' => 'Bleach, Vol. 36: Turn Back the Pendulum',
    'imagem_original' => 'bleach_36.jpg',
    'parcelas' => 1,
],
    12 => [
    'id_banco' => 12,
    'nome_original' => 'Bleach, Vol. 37: Beauty Is So Solitary',
    'imagem_original' => 'bleach_37.jpg',
    'parcelas' => 2,
],
    16 => [
    'id_banco' => 16,
    'nome_original' => 'Bleach vol. 4',
    'imagem_original' => 'bleach_4.jpg',
    'parcelas' => 2,
],
    65 => [
    'id_banco' => 65,
    'nome_original' => 'Anos 2000: O Renascimento Da Marvel Vol. 04 (de 10) - Capitão América',
    'imagem_original' => 'capitao_1.webp',
    'parcelas' => 1,
],
    66 => [
    'id_banco' => 66,
    'nome_original' => 'Capitão América Por Mark Waid E Chris Samnee',
    'imagem_original' => 'capitao_2.webp',
    'parcelas' => 2,
],
    67 => [
    'id_banco' => 67,
    'nome_original' => 'Capitão América E Os Vingadores 01',
    'imagem_original' => 'capitao_3.webp',
    'parcelas' => 1,
],
    68 => [
    'id_banco' => 68,
    'nome_original' => 'Coleção Clássica Marvel: Nova Fase Vol. 17 - Capitão América 6 - Se O Passado Não Estiver Morto!',
    'imagem_original' => 'capitao_4.webp',
    'parcelas' => 1,
],
    102 => [
    'id_banco' => 102,
    'nome_original' => 'O Asilo Do Coringa',
    'imagem_original' => 'coringa_1.webp',
    'parcelas' => 2,
],
    103 => [
    'id_banco' => 103,
    'nome_original' => 'Coringa: O Mundo',
    'imagem_original' => 'coringa_2.jpg',
    'parcelas' => 2,
],
    104 => [
    'id_banco' => 104,
    'nome_original' => 'Coringa: A Era De Bronze Omnibus',
    'imagem_original' => 'coringa_3.webp',
    'parcelas' => 5,
],
    105 => [
    'id_banco' => 105,
    'nome_original' => 'Coringa: O Homem Que Parou De Rir Vol. 1',
    'imagem_original' => 'coringa_4.jpg',
    'parcelas' => 2,
],
    21 => [
    'id_banco' => 21,
    'nome_original' => 'Demon slayer - Kimetsu No Yaiba vol. 1',
    'imagem_original' => 'demon_slayer_vol1.jpg',
    'parcelas' => 1,
],
    18 => [
    'id_banco' => 18,
    'nome_original' => 'Demon slayer - Kimetsu no Yaiba vol. 18',
    'imagem_original' => 'demon_slayer_vol18.jpg',
    'parcelas' => 1,
],
    19 => [
    'id_banco' => 19,
    'nome_original' => 'Demon Slayer: Kimetsu No Yaiba, Vol. 19',
    'imagem_original' => 'demon_slayer_vol19.jpg',
    'parcelas' => 1,
],
    22 => [
    'id_banco' => 22,
    'nome_original' => 'Demon slayer - Kimetsu No Yaiba vol. 2',
    'imagem_original' => 'demon_slayer_vol2.jpg',
    'parcelas' => 1,
],
    20 => [
    'id_banco' => 20,
    'nome_original' => 'Demon Slayer: Kimetsu No Yaiba, Vol. 20',
    'imagem_original' => 'demon_slayer_vol20.jpg',
    'parcelas' => 1,
],
    17 => [
    'id_banco' => 17,
    'nome_original' => 'Demon Slayer - Kimetsu no Yaiba Vol. 23',
    'imagem_original' => 'demonslayer_vol23.jpg',
    'parcelas' => 4,
],
    23 => [
    'id_banco' => 23,
    'nome_original' => 'Demon slayer - Kimetsu No Yaiba Vol. 3',
    'imagem_original' => 'demon_slayer_vol3.jpg',
    'parcelas' => 1,
],
    24 => [
    'id_banco' => 24,
    'nome_original' => 'Demon slayer - Kimetsu No Yaiba vol. 4',
    'imagem_original' => 'demon_slayer_vol4.jpg',
    'parcelas' => 1,
],
    69 => [
    'id_banco' => 69,
    'nome_original' => 'Doutor Estranho De Asgard',
    'imagem_original' => 'doutor_1.jpg',
    'parcelas' => 1,
],
    70 => [
    'id_banco' => 70,
    'nome_original' => 'Doutor Estranho (2024) 01',
    'imagem_original' => 'doutor_2.jpg',
    'parcelas' => 1,
],
    71 => [
    'id_banco' => 71,
    'nome_original' => 'Doutor Estranho: Princípio E Fim',
    'imagem_original' => 'doutor_3.jpg',
    'parcelas' => 2,
],
    72 => [
    'id_banco' => 72,
    'nome_original' => 'Doutor Estranho (2023) 01',
    'imagem_original' => 'doutor_4.jpg',
    'parcelas' => 1,
],
    29 => [
    'id_banco' => 29,
    'nome_original' => 'Dragon Ball - 01',
    'imagem_original' => 'dragon_ball_1.jpg',
    'parcelas' => 2,
],
    30 => [
    'id_banco' => 30,
    'nome_original' => 'Dragon Ball - 02',
    'imagem_original' => 'dragon_ball_2.jpg',
    'parcelas' => 1,
],
    31 => [
    'id_banco' => 31,
    'nome_original' => 'Dragon Ball - 03',
    'imagem_original' => 'dragon_ball_3.jpg',
    'parcelas' => 1,
],
    32 => [
    'id_banco' => 32,
    'nome_original' => 'Dragon Ball - 04',
    'imagem_original' => 'dragon_ball_4.jpg',
    'parcelas' => 2,
],
    28 => [
    'id_banco' => 28,
    'nome_original' => 'Dragon Ball - 39',
    'imagem_original' => 'dragon_ball_39.jpg',
    'parcelas' => 2,
],
    27 => [
    'id_banco' => 27,
    'nome_original' => 'Dragon Ball - 40',
    'imagem_original' => 'dragon_ball_40.jpg',
    'parcelas' => 2,
],
    26 => [
    'id_banco' => 26,
    'nome_original' => 'Dragon Ball - 41',
    'imagem_original' => 'dragon_ball_41.jpg',
    'parcelas' => 2,
],
    25 => [
    'id_banco' => 25,
    'nome_original' => 'Dragon Ball - 42',
    'imagem_original' => 'dragon_ball_42.jpg',
    'parcelas' => 2,
],
    106 => [
    'id_banco' => 106,
    'nome_original' => 'Flash: Ano Um',
    'imagem_original' => 'flash1.jpg',
    'parcelas' => 2,
],
    107 => [
    'id_banco' => 107,
    'nome_original' => 'Flash: Renascimento',
    'imagem_original' => 'flash2.jpg',
    'parcelas' => 2,
],
    108 => [
    'id_banco' => 108,
    'nome_original' => 'Flash: Ponto de Ignição',
    'imagem_original' => 'flash3.jpg',
    'parcelas' => 2,
],
    109 => [
    'id_banco' => 109,
    'nome_original' => 'Flash: A Guerra dos Flashes',
    'imagem_original' => 'flash4.jpg',
    'parcelas' => 2,
],
    73 => [
    'id_banco' => 73,
    'nome_original' => 'Hulk: A Tempestade (Marvel Essenciais)',
    'imagem_original' => 'hulk_1.webp',
    'parcelas' => 2,
],
    74 => [
    'id_banco' => 74,
    'nome_original' => 'A Saga Do Hulk 04',
    'imagem_original' => 'hulk_2.webp',
    'parcelas' => 1,
],
    75 => [
    'id_banco' => 75,
    'nome_original' => 'A Saga Do Hulk 06',
    'imagem_original' => 'hulk_3.webp',
    'parcelas' => 2,
],
    76 => [
    'id_banco' => 76,
    'nome_original' => 'O Incrível Hulk (2024) Vol. 02',
    'imagem_original' => 'hulk_4.png',
    'parcelas' => 1,
],
    77 => [
    'id_banco' => 77,
    'nome_original' => 'Tales of Suspense (1959-1968) #39',
    'imagem_original' => 'iron_man_1.jpg',
    'parcelas' => 3,
],
    78 => [
    'id_banco' => 78,
    'nome_original' => 'Invincible Iron Man Vol. 1: Reboot',
    'imagem_original' => 'iron_man_2.jpg',
    'parcelas' => 3,
],
    79 => [
    'id_banco' => 79,
    'nome_original' => 'O Invencível Homem De Ferro Omnibus Vol. 4',
    'imagem_original' => 'iron_man_3.webp',
    'parcelas' => 6,
],
    80 => [
    'id_banco' => 80,
    'nome_original' => 'Invincible Iron Man by Gerry Duggan Vol. 1: Demon In The Armor',
    'imagem_original' => 'iron_man_4.jpg',
    'parcelas' => 2,
],
    110 => [
    'id_banco' => 110,
    'nome_original' => 'Lanterna Verde (2024) 04',
    'imagem_original' => 'lanterna_1.webp',
    'parcelas' => 1,
],
    111 => [
    'id_banco' => 111,
    'nome_original' => 'Lanterna Verde (2024) 09',
    'imagem_original' => 'lanterna_2.webp',
    'parcelas' => 1,
],
    112 => [
    'id_banco' => 112,
    'nome_original' => 'Absolute Lanterna Verde 01',
    'imagem_original' => 'lanterna_3.webp',
    'parcelas' => 1,
],
    113 => [
    'id_banco' => 113,
    'nome_original' => 'Lanterna Verde (2025) 02',
    'imagem_original' => 'lanterna_4.webp',
    'parcelas' => 1,
],
    114 => [
    'id_banco' => 114,
    'nome_original' => 'Liga Da Justiça Vs Godzilla Vs Kong',
    'imagem_original' => 'liga_1.webp',
    'parcelas' => 1,
],
    115 => [
    'id_banco' => 115,
    'nome_original' => 'Liga Da Justiça Da América: Ano Um',
    'imagem_original' => 'liga_2.webp',
    'parcelas' => 2,
],
    116 => [
    'id_banco' => 116,
    'nome_original' => 'Liga Da Justiça Sem Limites (2025) 12',
    'imagem_original' => 'liga_3.webp',
    'parcelas' => 1,
],
    117 => [
    'id_banco' => 117,
    'nome_original' => 'A Saga Da Liga Da Justiça 03/19',
    'imagem_original' => 'liga_4.webp',
    'parcelas' => 1,
],
    118 => [
    'id_banco' => 118,
    'nome_original' => 'Mulher-Maravilha: Hiketeia',
    'imagem_original' => 'mulhermara_1.jpg',
    'parcelas' => 1,
],
    119 => [
    'id_banco' => 119,
    'nome_original' => 'Mulher-Maravilha: Evolução',
    'imagem_original' => 'mulhermara_2.jpg',
    'parcelas' => 1,
],
    120 => [
    'id_banco' => 120,
    'nome_original' => 'Mulher-Maravilha/Flash 15',
    'imagem_original' => 'mulhermara_3.jpg',
    'parcelas' => 1,
],
    121 => [
    'id_banco' => 121,
    'nome_original' => 'Absolute Mulher-Maravilha 04',
    'imagem_original' => 'mulhermara_4.jpg',
    'parcelas' => 1,
],
    37 => [
    'id_banco' => 37,
    'nome_original' => 'Naruto Gold - Vol. 1',
    'imagem_original' => 'narutogold_01.jpg',
    'parcelas' => 1,
],
    38 => [
    'id_banco' => 38,
    'nome_original' => 'Naruto Gold - Vol. 2',
    'imagem_original' => 'narutogold_02.jpg',
    'parcelas' => 1,
],
    39 => [
    'id_banco' => 39,
    'nome_original' => 'Naruto Gold - Vol. 3',
    'imagem_original' => 'narutogold_vol3.jpg',
    'parcelas' => 1,
],
    40 => [
    'id_banco' => 40,
    'nome_original' => 'Naruto Gold - Vol. 4',
    'imagem_original' => 'narutogold_04.jpg',
    'parcelas' => 1,
],
    35 => [
    'id_banco' => 35,
    'nome_original' => 'Naruto, Vol. 69',
    'imagem_original' => 'naruto_vol69.jpg',
    'parcelas' => 1,
],
    36 => [
    'id_banco' => 36,
    'nome_original' => 'Naruto, Vol. 70',
    'imagem_original' => 'naruto_vol70.webp',
    'parcelas' => 1,
],
    34 => [
    'id_banco' => 34,
    'nome_original' => 'Naruto, Vol. 71: Eu Amo Vocês',
    'imagem_original' => 'naruto_vol71.jpg',
    'parcelas' => 2,
],
    33 => [
    'id_banco' => 33,
    'nome_original' => 'Naruto, Vol. 72',
    'imagem_original' => 'naruto_vol72.jpg',
    'parcelas' => 3,
],
    41 => [
    'id_banco' => 41,
    'nome_original' => 'One Piece Vol.67',
    'imagem_original' => 'one_piece_67.jpg',
    'parcelas' => 2,
],
    45 => [
    'id_banco' => 45,
    'nome_original' => 'One Piece Vol.1',
    'imagem_original' => 'onepiece_vol1.jpg',
    'parcelas' => 1,
],
    46 => [
    'id_banco' => 46,
    'nome_original' => 'One Piece Vol.2',
    'imagem_original' => 'onepiece_vol2.jpg',
    'parcelas' => 1,
],
    47 => [
    'id_banco' => 47,
    'nome_original' => 'One Piece Vol.3',
    'imagem_original' => 'onepiece_vol3.jpg',
    'parcelas' => 1,
],
    48 => [
    'id_banco' => 48,
    'nome_original' => 'One Piece Vol.4',
    'imagem_original' => 'onepiece_vol4.jpg',
    'parcelas' => 1,
],
    43 => [
    'id_banco' => 43,
    'nome_original' => 'One Piece Vol.64',
    'imagem_original' => 'onepiece_vol64.jpg',
    'parcelas' => 2,
],
    44 => [
    'id_banco' => 44,
    'nome_original' => 'One Piece Vol.65',
    'imagem_original' => 'onepiece_vol65.jpg',
    'parcelas' => 2,
],
    42 => [
    'id_banco' => 42,
    'nome_original' => 'One Piece Vol.66',
    'imagem_original' => 'onepiece_vol66.jpg',
    'parcelas' => 3,
],
    200021 => [
    'id_banco' => 200021,
    'nome_original' => 'Quarteto Fantástico (2023) Vol. 6',
    'imagem_original' => 'quarteto_1.webp',
    'parcelas' => 1,
    'categoria_id' => 2,
    'nome' => 'Quarteto Fantástico (2023) Vol. 6',
    'imagem' => 'quarteto_1.webp',
    'autor' => 'Ryan North, Carlos Gómez e Ivan Fiorelli',
    'ano_publicacao' => 2026,
    'paginas' => 120,
    'isbn' => '9786525953083',
    'editora' => 'Panini',
    'descricao' => '',
    'preco' => 0,
],
    200022 => [
    'id_banco' => 200022,
    'nome_original' => 'Marvel-Verse: Quarteto Fantástico',
    'imagem_original' => 'quarteto_2.webp',
    'parcelas' => 1,
    'categoria_id' => 2,
    'nome' => 'Marvel-Verse: Quarteto Fantástico',
    'imagem' => 'quarteto_2.webp',
    'autor' => 'Stan Lee, Jack Kirby, John Byrne, Roberto Aguirre-Sacasa e outros',
    'ano_publicacao' => 2026,
    'paginas' => 120,
    'isbn' => '9786525943923',
    'editora' => 'Panini',
    'descricao' => '',
    'preco' => 0,
],
    200023 => [
    'id_banco' => 200023,
    'nome_original' => 'Quarteto Fantástico (2023) Vol. 4',
    'imagem_original' => 'quarteto_3.webp',
    'parcelas' => 1,
    'categoria_id' => 2,
    'nome' => 'Quarteto Fantástico (2023) Vol. 4',
    'imagem' => 'quarteto_3.webp',
    'autor' => 'Ryan North, Iban Coello e Ivan Fiorelli',
    'ano_publicacao' => 2026,
    'paginas' => 144,
    'isbn' => '9786525935430',
    'editora' => 'Panini',
    'descricao' => '',
    'preco' => 0,
],
    200024 => [
    'id_banco' => 200024,
    'nome_original' => 'Quarteto Fantástico (2023) Vol. 1',
    'imagem_original' => 'quarteto_4.webp',
    'parcelas' => 1,
    'categoria_id' => 2,
    'nome' => 'Quarteto Fantástico (2023) Vol. 1',
    'imagem' => 'quarteto_4.webp',
    'autor' => 'Ryan North e Iban Coello',
    'ano_publicacao' => 2025,
    'paginas' => 152,
    'isbn' => '9786525905846',
    'editora' => 'Panini',
    'descricao' => '',
    'preco' => 0,
],
    82 => [
    'id_banco' => 82,
    'nome_original' => 'The Amazing Spider-Man #1',
    'imagem_original' => 'the_amazing_1.jpg',
    'parcelas' => 2,
],
    83 => [
    'id_banco' => 83,
    'nome_original' => 'The Amazing Spider-Man #2',
    'imagem_original' => 'the_amazing_2.jpg',
    'parcelas' => 2,
],
    84 => [
    'id_banco' => 84,
    'nome_original' => 'Amazing Spider-Man Omnibus Vol. 3',
    'imagem_original' => 'the_amazing_3.jpg',
    'parcelas' => 4,
],
    81 => [
    'id_banco' => 81,
    'nome_original' => 'Amazing Fantasy #15',
    'imagem_original' => 'amazing_fantasy.jpg',
    'parcelas' => 2,
],
    122 => [
    'id_banco' => 122,
    'nome_original' => 'Superman: Ano Um',
    'imagem_original' => 'superman_1.jpg',
    'parcelas' => 2,
],
    123 => [
    'id_banco' => 123,
    'nome_original' => 'Superman: As Quatro Estações (DC De Bolso)',
    'imagem_original' => 'superman_2.jpg',
    'parcelas' => 1,
],
    124 => [
    'id_banco' => 124,
    'nome_original' => 'Superman: Grandes Astros',
    'imagem_original' => 'superman_3.jpg',
    'parcelas' => 2,
],
    125 => [
    'id_banco' => 125,
    'nome_original' => 'A Morte do Superman',
    'imagem_original' => 'superman_4.jpg',
    'parcelas' => 1,
],
    85 => [
    'id_banco' => 85,
    'nome_original' => 'Thor: O Renascer dos Deuses: Marvel Essenciais',
    'imagem_original' => 'thor_1.jpg',
    'parcelas' => 2,
],
    86 => [
    'id_banco' => 86,
    'nome_original' => 'Thor Filho De Asgard Vol. 1',
    'imagem_original' => 'thor_2.jpg',
    'parcelas' => 1,
],
    87 => [
    'id_banco' => 87,
    'nome_original' => 'Thor: O Deus Do Trovão Renasce',
    'imagem_original' => 'thor_3.jpg',
    'parcelas' => 3,
],
    88 => [
    'id_banco' => 88,
    'nome_original' => 'Thor: Vikings',
    'imagem_original' => 'thor_4.jpg',
    'parcelas' => 2,
],
    53 => [
    'id_banco' => 53,
    'nome_original' => 'Tokyo Ghoul, Vol. 1',
    'imagem_original' => 'tokyoghoul_vol1.jpg',
    'parcelas' => 2,
],
    52 => [
    'id_banco' => 52,
    'nome_original' => 'Tokyo ghoul: re vol. 13',
    'imagem_original' => 'tokyoghoul_vol13.jpg',
    'parcelas' => 1,
],
    51 => [
    'id_banco' => 51,
    'nome_original' => 'Tokyo ghoul: re vol. 14',
    'imagem_original' => 'tokyoghoul_vol14.jpg',
    'parcelas' => 1,
],
    50 => [
    'id_banco' => 50,
    'nome_original' => 'Tokyo ghoul: re vol. 15',
    'imagem_original' => 'tokyoghoul_vol15.jpg',
    'parcelas' => 1,
],
    49 => [
    'id_banco' => 49,
    'nome_original' => 'Tokyo ghoul: re vol. 16',
    'imagem_original' => 'tokyoghoul_vol16.jpg',
    'parcelas' => 1,
],
    54 => [
    'id_banco' => 54,
    'nome_original' => 'Tokyo Ghoul, Vol. 2',
    'imagem_original' => 'tokyoghoul_vol2.jpg',
    'parcelas' => 1,
],
    55 => [
    'id_banco' => 55,
    'nome_original' => 'Tokyo Ghoul, Vol. 3',
    'imagem_original' => 'tokyoghoul_vol3.jpg',
    'parcelas' => 1,
],
    56 => [
    'id_banco' => 56,
    'nome_original' => 'Tokyo Ghoul, Vol. 4',
    'imagem_original' => 'tokyoghoul_vol4.jpg',
    'parcelas' => 1,
],
    89 => [
    'id_banco' => 89,
    'nome_original' => 'Os Vingadores Vol. 55',
    'imagem_original' => 'vingadores_1.png',
    'parcelas' => 1,
],
    90 => [
    'id_banco' => 90,
    'nome_original' => 'Os Vingadores 20/77',
    'imagem_original' => 'vingadores_2.webp',
    'parcelas' => 1,
],
    91 => [
    'id_banco' => 91,
    'nome_original' => 'Vingadores: Beyonder',
    'imagem_original' => 'vingadores_3.png',
    'parcelas' => 1,
],
    92 => [
    'id_banco' => 92,
    'nome_original' => 'Os Vingadores Vol. 54',
    'imagem_original' => 'vingadores_4.png',
    'parcelas' => 1,
],
    61 => [
    'id_banco' => 61,
    'nome_original' => 'Vinland Saga Deluxe Vol. 1',
    'imagem_original' => 'vinland_saga_vol1.png',
    'parcelas' => 1,
],
    62 => [
    'id_banco' => 62,
    'nome_original' => 'Vinland Saga Deluxe Vol. 2',
    'imagem_original' => 'vinland-saga-deluxe-vol-2.webp',
    'parcelas' => 1,
],
    60 => [
    'id_banco' => 60,
    'nome_original' => 'Vinland saga vol. 26',
    'imagem_original' => 'vinland_saga_vol26.png',
    'parcelas' => 1,
],
    59 => [
    'id_banco' => 59,
    'nome_original' => 'Vinland saga vol. 27',
    'imagem_original' => 'vinland_saga_vol27.png',
    'parcelas' => 1,
],
    58 => [
    'id_banco' => 58,
    'nome_original' => 'Vinland saga vol. 28',
    'imagem_original' => 'vinland_saga_vol28.png',
    'parcelas' => 1,
],
    57 => [
    'id_banco' => 57,
    'nome_original' => 'Vinland saga vol. 29',
    'imagem_original' => 'vinland_saga_vol29.png',
    'parcelas' => 1,
],
    63 => [
    'id_banco' => 63,
    'nome_original' => 'Vinland Saga Deluxe Vol. 3',
    'imagem_original' => 'vinland_saga_vol3.png',
    'parcelas' => 2,
],
    64 => [
    'id_banco' => 64,
    'nome_original' => 'Vinland Saga Deluxe Vol. 4',
    'imagem_original' => 'vinland_saga_vol4.png',
    'parcelas' => 2,
],
];
