<?php
// Endereços anteriores preservados durante a reorganização.
return [
    'Projeto/login.php' => 'Projeto/conta/login.php',
    'Projeto/logout.php' => 'Projeto/conta/logout.php',
    'Projeto/registrar.php' => 'Projeto/conta/registrar.php',
    'Projeto/meuPerfil.php' => 'Projeto/conta/meuPerfil.php',
    'Projeto/meusPedidos.php' => 'Projeto/conta/meusPedidos.php',
    'Projeto/encerrarConta.php' => 'Projeto/conta/encerrarConta.php',
    'Projeto/recuperar_senha.php' => 'Projeto/conta/recuperar_senha.php',
    'Projeto/redefinir_senha.php' => 'Projeto/conta/redefinir_senha.php',
    'Projeto/carrinho.php' => 'Projeto/carrinho/carrinho.php',
    'Projeto/carrinho_adicionar.php' => 'Projeto/carrinho/carrinho_adicionar.php',
    'Projeto/carrinho_atualizar.php' => 'Projeto/carrinho/carrinho_atualizar.php',
    'Projeto/carrinho_remover.php' => 'Projeto/carrinho/carrinho_remover.php',
    'Projeto/checkout.php' => 'Projeto/carrinho/checkout.php',
    'Projeto/contato.php' => 'Projeto/institucional/contato.php',
    'Projeto/metodos-pagamento.php' => 'Projeto/institucional/metodos-pagamento.php',
    'Projeto/perguntas-frequentes.php' => 'Projeto/institucional/perguntas-frequentes.php',
    'Projeto/politica-cookies.php' => 'Projeto/institucional/politica-cookies.php',
    'Projeto/politica-privacidade.php' => 'Projeto/institucional/politica-privacidade.php',
    'Projeto/prazos-entrega.php' => 'Projeto/institucional/prazos-entrega.php',
    'Projeto/regulamentos.php' => 'Projeto/institucional/regulamentos.php',
    'Projeto/termos-condicoes.php' => 'Projeto/institucional/termos-condicoes.php',
    'Projeto/newsletter.php' => 'Projeto/institucional/newsletter.php',
    'Projeto/AddProduto.php' => 'Projeto/Admin/legado/AddProduto.php',
    'Projeto/editar.php' => 'Projeto/Admin/legado/editar.php',
    'Projeto/editarCadastro.php' => 'Projeto/Admin/legado/editarCadastro.php',
    'Projeto/estoque.php' => 'Projeto/Admin/legado/estoque.php',
    'Projeto/excluir.php' => 'Projeto/Admin/legado/excluir.php',
    'Projeto/index.php' => 'Projeto/Admin/legado/index.php',
    'Projeto/conexao.php' => 'Projeto/Arquivos/conexao_conta.php',
    'Projeto/verificarAdmin.php' => 'Projeto/Arquivos/verificarAdmin_legado.php',
    'Projeto/verificarLogin.php' => 'Projeto/Arquivos/verificarLogin_legado.php',
];
